//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class odataEntities : DbContext
    {
        public odataEntities()
            : base("name=odataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attributes> Attributes { get; set; }
        public DbSet<ClassTab> ClassTab { get; set; }
        public DbSet<EMP> EMP { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<test> test { get; set; }
        public DbSet<WORK> WORK { get; set; }
        public DbSet<V_Student> V_Student { get; set; }
        public DbSet<YHTAB> YHTAB { get; set; }
    }
}
