//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Sex { get; set; }
        public decimal Chinese { get; set; }
        public decimal Math { get; set; }
        public decimal English { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string Expr1 { get; set; }
    }
}
