//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http.Cors;
using System.Web.Http;
using System.Web.Http.OData.Builder;
using System.Web.Http.OData.Extensions;
using OdataExample.Models;
namespace OdataExample{
 public partial class WebApiConfig
{
       public static void Register(HttpConfiguration config)
        {
            // Web API 配置和服务
            config.EnableCors(new EnableCorsAttribute("*", "*", "*"));
            // Web API 路由
            ODataModelBuilder builder = new ODataConventionModelBuilder();
				        builder.EntitySet<Attributes>("Attributes");
	        	        builder.EntitySet<ClassTab>("ClassTab");
	        	        builder.EntitySet<EMP>("EMP");
	        	        builder.EntitySet<Student>("Student");
	        	        builder.EntitySet<test>("test");
	        	        builder.EntitySet<V_Student>("V_Student");
	        	        builder.EntitySet<WORK>("WORK");
	        	        builder.EntitySet<YHTAB>("YHTAB");
	                    config.Routes.MapODataServiceRoute("odata", "odata", builder.GetEdmModel());
        }
  
}
}
