//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class APP_CAROUSELController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/APP_CAROUSEL
            [EnableQuery]
            public IQueryable<APP_CAROUSEL> GetAPP_CAROUSEL()
            {
                return db.APP_CAROUSEL;
            }
    
            // GET: odata/APP_CAROUSEL(5)
            [EnableQuery]
            public SingleResult<APP_CAROUSEL> GetAPP_CAROUSEL([FromODataUri] string key)
            {
                return SingleResult.Create(db.APP_CAROUSEL.Where(w => w.CDID == key));
            }
    
            // PUT: odata/APP_CAROUSEL(5)
            public IHttpActionResult Put([FromODataUri] string key, Delta<APP_CAROUSEL> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                APP_CAROUSEL APP_CAROUSEL = db.APP_CAROUSEL.Find(key);
                if (APP_CAROUSEL == null)
                {
                    return NotFound();
                }
    
                patch.Put(APP_CAROUSEL);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!APP_CAROUSELExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(APP_CAROUSEL);
            }
    
            // POST: odata/APP_CAROUSEL
            public IHttpActionResult Post(APP_CAROUSEL APP_CAROUSEL)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.APP_CAROUSEL.Add(APP_CAROUSEL);
                db.SaveChanges();
    
                return Created(APP_CAROUSEL);
            }
    
            // PATCH: odata/APP_CAROUSEL(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] string key, Delta<APP_CAROUSEL> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                APP_CAROUSEL APP_CAROUSEL = db.APP_CAROUSEL.Find(key);
                if (APP_CAROUSEL == null)
                {
                    return NotFound();
                }
    
                patch.Patch(APP_CAROUSEL);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!APP_CAROUSELExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(APP_CAROUSEL);
            }
    
            // DELETE: odata/APP_CAROUSEL(5)
            public IHttpActionResult Delete([FromODataUri] string key)
            {
                APP_CAROUSEL APP_CAROUSEL = db.APP_CAROUSEL.Find(key);
                if (APP_CAROUSEL == null)
                {
                    return NotFound();
                }
    
                db.APP_CAROUSEL.Remove(APP_CAROUSEL);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool APP_CAROUSELExists(string key)
            {
                return db.APP_CAROUSEL.Count(e => e.CDID == key) > 0;
            }
      
    }
}
