//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class EASONController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/EASON
            [EnableQuery]
            public IQueryable<EASON> GetEASON()
            {
                return db.EASON;
            }
    
            // GET: odata/EASON(5)
            [EnableQuery]
            public SingleResult<EASON> GetEASON([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.EASON.Where(w => w.ID == key));
            }
    
            // PUT: odata/EASON(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<EASON> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                EASON EASON = db.EASON.Find(key);
                if (EASON == null)
                {
                    return NotFound();
                }
    
                patch.Put(EASON);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EASONExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(EASON);
            }
    
            // POST: odata/EASON
            public IHttpActionResult Post(EASON EASON)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.EASON.Add(EASON);
                db.SaveChanges();
    
                return Created(EASON);
            }
    
            // PATCH: odata/EASON(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<EASON> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                EASON EASON = db.EASON.Find(key);
                if (EASON == null)
                {
                    return NotFound();
                }
    
                patch.Patch(EASON);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EASONExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(EASON);
            }
    
            // DELETE: odata/EASON(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                EASON EASON = db.EASON.Find(key);
                if (EASON == null)
                {
                    return NotFound();
                }
    
                db.EASON.Remove(EASON);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool EASONExists(decimal key)
            {
                return db.EASON.Count(e => e.ID == key) > 0;
            }
      
    }
}
