//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class KJDW_TESTController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/KJDW_TEST
            [EnableQuery]
            public IQueryable<KJDW_TEST> GetKJDW_TEST()
            {
                return db.KJDW_TEST;
            }
    
            // GET: odata/KJDW_TEST(5)
            [EnableQuery]
            public SingleResult<KJDW_TEST> GetKJDW_TEST([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.KJDW_TEST.Where(w => w.OBJECTID == key));
            }
    
            // PUT: odata/KJDW_TEST(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<KJDW_TEST> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                KJDW_TEST KJDW_TEST = db.KJDW_TEST.Find(key);
                if (KJDW_TEST == null)
                {
                    return NotFound();
                }
    
                patch.Put(KJDW_TEST);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KJDW_TESTExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(KJDW_TEST);
            }
    
            // POST: odata/KJDW_TEST
            public IHttpActionResult Post(KJDW_TEST KJDW_TEST)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.KJDW_TEST.Add(KJDW_TEST);
                db.SaveChanges();
    
                return Created(KJDW_TEST);
            }
    
            // PATCH: odata/KJDW_TEST(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<KJDW_TEST> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                KJDW_TEST KJDW_TEST = db.KJDW_TEST.Find(key);
                if (KJDW_TEST == null)
                {
                    return NotFound();
                }
    
                patch.Patch(KJDW_TEST);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KJDW_TESTExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(KJDW_TEST);
            }
    
            // DELETE: odata/KJDW_TEST(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                KJDW_TEST KJDW_TEST = db.KJDW_TEST.Find(key);
                if (KJDW_TEST == null)
                {
                    return NotFound();
                }
    
                db.KJDW_TEST.Remove(KJDW_TEST);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool KJDW_TESTExists(decimal key)
            {
                return db.KJDW_TEST.Count(e => e.OBJECTID == key) > 0;
            }
      
    }
}
