//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class T_ADMIN_LICENSEController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/T_ADMIN_LICENSE
            [EnableQuery]
            public IQueryable<T_ADMIN_LICENSE> GetT_ADMIN_LICENSE()
            {
                return db.T_ADMIN_LICENSE;
            }
    
            // GET: odata/T_ADMIN_LICENSE(5)
            [EnableQuery]
            public SingleResult<T_ADMIN_LICENSE> GetT_ADMIN_LICENSE([FromODataUri] string key)
            {
                return SingleResult.Create(db.T_ADMIN_LICENSE.Where(w => w.S_ID == key));
            }
    
            // PUT: odata/T_ADMIN_LICENSE(5)
            public IHttpActionResult Put([FromODataUri] string key, Delta<T_ADMIN_LICENSE> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_ADMIN_LICENSE T_ADMIN_LICENSE = db.T_ADMIN_LICENSE.Find(key);
                if (T_ADMIN_LICENSE == null)
                {
                    return NotFound();
                }
    
                patch.Put(T_ADMIN_LICENSE);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_ADMIN_LICENSEExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_ADMIN_LICENSE);
            }
    
            // POST: odata/T_ADMIN_LICENSE
            public IHttpActionResult Post(T_ADMIN_LICENSE T_ADMIN_LICENSE)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.T_ADMIN_LICENSE.Add(T_ADMIN_LICENSE);
                db.SaveChanges();
    
                return Created(T_ADMIN_LICENSE);
            }
    
            // PATCH: odata/T_ADMIN_LICENSE(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] string key, Delta<T_ADMIN_LICENSE> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_ADMIN_LICENSE T_ADMIN_LICENSE = db.T_ADMIN_LICENSE.Find(key);
                if (T_ADMIN_LICENSE == null)
                {
                    return NotFound();
                }
    
                patch.Patch(T_ADMIN_LICENSE);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_ADMIN_LICENSEExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_ADMIN_LICENSE);
            }
    
            // DELETE: odata/T_ADMIN_LICENSE(5)
            public IHttpActionResult Delete([FromODataUri] string key)
            {
                T_ADMIN_LICENSE T_ADMIN_LICENSE = db.T_ADMIN_LICENSE.Find(key);
                if (T_ADMIN_LICENSE == null)
                {
                    return NotFound();
                }
    
                db.T_ADMIN_LICENSE.Remove(T_ADMIN_LICENSE);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool T_ADMIN_LICENSEExists(string key)
            {
                return db.T_ADMIN_LICENSE.Count(e => e.S_ID == key) > 0;
            }
      
    }
}
