//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class T_FXQLCZController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/T_FXQLCZ
            [EnableQuery]
            public IQueryable<T_FXQLCZ> GetT_FXQLCZ()
            {
                return db.T_FXQLCZ;
            }
    
            // GET: odata/T_FXQLCZ(5)
            [EnableQuery]
            public SingleResult<T_FXQLCZ> GetT_FXQLCZ([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.T_FXQLCZ.Where(w => w.OBJECTID == key));
            }
    
            // PUT: odata/T_FXQLCZ(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<T_FXQLCZ> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_FXQLCZ T_FXQLCZ = db.T_FXQLCZ.Find(key);
                if (T_FXQLCZ == null)
                {
                    return NotFound();
                }
    
                patch.Put(T_FXQLCZ);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_FXQLCZExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_FXQLCZ);
            }
    
            // POST: odata/T_FXQLCZ
            public IHttpActionResult Post(T_FXQLCZ T_FXQLCZ)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.T_FXQLCZ.Add(T_FXQLCZ);
                db.SaveChanges();
    
                return Created(T_FXQLCZ);
            }
    
            // PATCH: odata/T_FXQLCZ(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<T_FXQLCZ> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_FXQLCZ T_FXQLCZ = db.T_FXQLCZ.Find(key);
                if (T_FXQLCZ == null)
                {
                    return NotFound();
                }
    
                patch.Patch(T_FXQLCZ);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_FXQLCZExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_FXQLCZ);
            }
    
            // DELETE: odata/T_FXQLCZ(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                T_FXQLCZ T_FXQLCZ = db.T_FXQLCZ.Find(key);
                if (T_FXQLCZ == null)
                {
                    return NotFound();
                }
    
                db.T_FXQLCZ.Remove(T_FXQLCZ);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool T_FXQLCZExists(decimal key)
            {
                return db.T_FXQLCZ.Count(e => e.OBJECTID == key) > 0;
            }
      
    }
}
