//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class T_FXTD2Controller:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/T_FXTD2
            [EnableQuery]
            public IQueryable<T_FXTD2> GetT_FXTD2()
            {
                return db.T_FXTD2;
            }
    
            // GET: odata/T_FXTD2(5)
            [EnableQuery]
            public SingleResult<T_FXTD2> GetT_FXTD2([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.T_FXTD2.Where(w => w.OBJECTID == key));
            }
    
            // PUT: odata/T_FXTD2(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<T_FXTD2> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_FXTD2 T_FXTD2 = db.T_FXTD2.Find(key);
                if (T_FXTD2 == null)
                {
                    return NotFound();
                }
    
                patch.Put(T_FXTD2);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_FXTD2Exists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_FXTD2);
            }
    
            // POST: odata/T_FXTD2
            public IHttpActionResult Post(T_FXTD2 T_FXTD2)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.T_FXTD2.Add(T_FXTD2);
                db.SaveChanges();
    
                return Created(T_FXTD2);
            }
    
            // PATCH: odata/T_FXTD2(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<T_FXTD2> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_FXTD2 T_FXTD2 = db.T_FXTD2.Find(key);
                if (T_FXTD2 == null)
                {
                    return NotFound();
                }
    
                patch.Patch(T_FXTD2);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_FXTD2Exists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_FXTD2);
            }
    
            // DELETE: odata/T_FXTD2(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                T_FXTD2 T_FXTD2 = db.T_FXTD2.Find(key);
                if (T_FXTD2 == null)
                {
                    return NotFound();
                }
    
                db.T_FXTD2.Remove(T_FXTD2);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool T_FXTD2Exists(decimal key)
            {
                return db.T_FXTD2.Count(e => e.OBJECTID == key) > 0;
            }
      
    }
}
