//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class T_GPBZController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/T_GPBZ
            [EnableQuery]
            public IQueryable<T_GPBZ> GetT_GPBZ()
            {
                return db.T_GPBZ;
            }
    
            // GET: odata/T_GPBZ(5)
            [EnableQuery]
            public SingleResult<T_GPBZ> GetT_GPBZ([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.T_GPBZ.Where(w => w.OBJECTID_12 == key));
            }
    
            // PUT: odata/T_GPBZ(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<T_GPBZ> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_GPBZ T_GPBZ = db.T_GPBZ.Find(key);
                if (T_GPBZ == null)
                {
                    return NotFound();
                }
    
                patch.Put(T_GPBZ);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_GPBZExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_GPBZ);
            }
    
            // POST: odata/T_GPBZ
            public IHttpActionResult Post(T_GPBZ T_GPBZ)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.T_GPBZ.Add(T_GPBZ);
                db.SaveChanges();
    
                return Created(T_GPBZ);
            }
    
            // PATCH: odata/T_GPBZ(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<T_GPBZ> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_GPBZ T_GPBZ = db.T_GPBZ.Find(key);
                if (T_GPBZ == null)
                {
                    return NotFound();
                }
    
                patch.Patch(T_GPBZ);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_GPBZExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_GPBZ);
            }
    
            // DELETE: odata/T_GPBZ(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                T_GPBZ T_GPBZ = db.T_GPBZ.Find(key);
                if (T_GPBZ == null)
                {
                    return NotFound();
                }
    
                db.T_GPBZ.Remove(T_GPBZ);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool T_GPBZExists(decimal key)
            {
                return db.T_GPBZ.Count(e => e.OBJECTID_12 == key) > 0;
            }
      
    }
}
