//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class T_HYDROLOGYSTATIONController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/T_HYDROLOGYSTATION
            [EnableQuery]
            public IQueryable<T_HYDROLOGYSTATION> GetT_HYDROLOGYSTATION()
            {
                return db.T_HYDROLOGYSTATION;
            }
    
            // GET: odata/T_HYDROLOGYSTATION(5)
            [EnableQuery]
            public SingleResult<T_HYDROLOGYSTATION> GetT_HYDROLOGYSTATION([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.T_HYDROLOGYSTATION.Where(w => w.OBJECTID == key));
            }
    
            // PUT: odata/T_HYDROLOGYSTATION(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<T_HYDROLOGYSTATION> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_HYDROLOGYSTATION T_HYDROLOGYSTATION = db.T_HYDROLOGYSTATION.Find(key);
                if (T_HYDROLOGYSTATION == null)
                {
                    return NotFound();
                }
    
                patch.Put(T_HYDROLOGYSTATION);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_HYDROLOGYSTATIONExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_HYDROLOGYSTATION);
            }
    
            // POST: odata/T_HYDROLOGYSTATION
            public IHttpActionResult Post(T_HYDROLOGYSTATION T_HYDROLOGYSTATION)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.T_HYDROLOGYSTATION.Add(T_HYDROLOGYSTATION);
                db.SaveChanges();
    
                return Created(T_HYDROLOGYSTATION);
            }
    
            // PATCH: odata/T_HYDROLOGYSTATION(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<T_HYDROLOGYSTATION> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_HYDROLOGYSTATION T_HYDROLOGYSTATION = db.T_HYDROLOGYSTATION.Find(key);
                if (T_HYDROLOGYSTATION == null)
                {
                    return NotFound();
                }
    
                patch.Patch(T_HYDROLOGYSTATION);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_HYDROLOGYSTATIONExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_HYDROLOGYSTATION);
            }
    
            // DELETE: odata/T_HYDROLOGYSTATION(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                T_HYDROLOGYSTATION T_HYDROLOGYSTATION = db.T_HYDROLOGYSTATION.Find(key);
                if (T_HYDROLOGYSTATION == null)
                {
                    return NotFound();
                }
    
                db.T_HYDROLOGYSTATION.Remove(T_HYDROLOGYSTATION);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool T_HYDROLOGYSTATIONExists(decimal key)
            {
                return db.T_HYDROLOGYSTATION.Count(e => e.OBJECTID == key) > 0;
            }
      
    }
}
