//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class T_PPTN_RController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/T_PPTN_R
            [EnableQuery]
            public IQueryable<T_PPTN_R> GetT_PPTN_R()
            {
                return db.T_PPTN_R;
            }
    
            // GET: odata/T_PPTN_R(5)
            [EnableQuery]
            public SingleResult<T_PPTN_R> GetT_PPTN_R([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.T_PPTN_R.Where(w => w.N_ID == key));
            }
    
            // PUT: odata/T_PPTN_R(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<T_PPTN_R> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_PPTN_R T_PPTN_R = db.T_PPTN_R.Find(key);
                if (T_PPTN_R == null)
                {
                    return NotFound();
                }
    
                patch.Put(T_PPTN_R);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_PPTN_RExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_PPTN_R);
            }
    
            // POST: odata/T_PPTN_R
            public IHttpActionResult Post(T_PPTN_R T_PPTN_R)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.T_PPTN_R.Add(T_PPTN_R);
                db.SaveChanges();
    
                return Created(T_PPTN_R);
            }
    
            // PATCH: odata/T_PPTN_R(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<T_PPTN_R> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_PPTN_R T_PPTN_R = db.T_PPTN_R.Find(key);
                if (T_PPTN_R == null)
                {
                    return NotFound();
                }
    
                patch.Patch(T_PPTN_R);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_PPTN_RExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_PPTN_R);
            }
    
            // DELETE: odata/T_PPTN_R(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                T_PPTN_R T_PPTN_R = db.T_PPTN_R.Find(key);
                if (T_PPTN_R == null)
                {
                    return NotFound();
                }
    
                db.T_PPTN_R.Remove(T_PPTN_R);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool T_PPTN_RExists(decimal key)
            {
                return db.T_PPTN_R.Count(e => e.N_ID == key) > 0;
            }
      
    }
}
