//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class T_PUMP_GRID_20170505Controller:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/T_PUMP_GRID_20170505
            [EnableQuery]
            public IQueryable<T_PUMP_GRID_20170505> GetT_PUMP_GRID_20170505()
            {
                return db.T_PUMP_GRID_20170505;
            }
    
            // GET: odata/T_PUMP_GRID_20170505(5)
            [EnableQuery]
            public SingleResult<T_PUMP_GRID_20170505> GetT_PUMP_GRID_20170505([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.T_PUMP_GRID_20170505.Where(w => w.OBJECTID == key));
            }
    
            // PUT: odata/T_PUMP_GRID_20170505(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<T_PUMP_GRID_20170505> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_PUMP_GRID_20170505 T_PUMP_GRID_20170505 = db.T_PUMP_GRID_20170505.Find(key);
                if (T_PUMP_GRID_20170505 == null)
                {
                    return NotFound();
                }
    
                patch.Put(T_PUMP_GRID_20170505);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_PUMP_GRID_20170505Exists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_PUMP_GRID_20170505);
            }
    
            // POST: odata/T_PUMP_GRID_20170505
            public IHttpActionResult Post(T_PUMP_GRID_20170505 T_PUMP_GRID_20170505)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.T_PUMP_GRID_20170505.Add(T_PUMP_GRID_20170505);
                db.SaveChanges();
    
                return Created(T_PUMP_GRID_20170505);
            }
    
            // PATCH: odata/T_PUMP_GRID_20170505(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<T_PUMP_GRID_20170505> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_PUMP_GRID_20170505 T_PUMP_GRID_20170505 = db.T_PUMP_GRID_20170505.Find(key);
                if (T_PUMP_GRID_20170505 == null)
                {
                    return NotFound();
                }
    
                patch.Patch(T_PUMP_GRID_20170505);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_PUMP_GRID_20170505Exists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_PUMP_GRID_20170505);
            }
    
            // DELETE: odata/T_PUMP_GRID_20170505(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                T_PUMP_GRID_20170505 T_PUMP_GRID_20170505 = db.T_PUMP_GRID_20170505.Find(key);
                if (T_PUMP_GRID_20170505 == null)
                {
                    return NotFound();
                }
    
                db.T_PUMP_GRID_20170505.Remove(T_PUMP_GRID_20170505);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool T_PUMP_GRID_20170505Exists(decimal key)
            {
                return db.T_PUMP_GRID_20170505.Count(e => e.OBJECTID == key) > 0;
            }
      
    }
}
