//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class T_RIVERController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/T_RIVER
            [EnableQuery]
            public IQueryable<T_RIVER> GetT_RIVER()
            {
                return db.T_RIVER;
            }
    
            // GET: odata/T_RIVER(5)
            [EnableQuery]
            public SingleResult<T_RIVER> GetT_RIVER([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.T_RIVER.Where(w => w.OBJECTID == key));
            }
    
            // PUT: odata/T_RIVER(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<T_RIVER> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_RIVER T_RIVER = db.T_RIVER.Find(key);
                if (T_RIVER == null)
                {
                    return NotFound();
                }
    
                patch.Put(T_RIVER);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_RIVERExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_RIVER);
            }
    
            // POST: odata/T_RIVER
            public IHttpActionResult Post(T_RIVER T_RIVER)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.T_RIVER.Add(T_RIVER);
                db.SaveChanges();
    
                return Created(T_RIVER);
            }
    
            // PATCH: odata/T_RIVER(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<T_RIVER> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_RIVER T_RIVER = db.T_RIVER.Find(key);
                if (T_RIVER == null)
                {
                    return NotFound();
                }
    
                patch.Patch(T_RIVER);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_RIVERExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_RIVER);
            }
    
            // DELETE: odata/T_RIVER(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                T_RIVER T_RIVER = db.T_RIVER.Find(key);
                if (T_RIVER == null)
                {
                    return NotFound();
                }
    
                db.T_RIVER.Remove(T_RIVER);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool T_RIVERExists(decimal key)
            {
                return db.T_RIVER.Count(e => e.OBJECTID == key) > 0;
            }
      
    }
}
