//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class T_SEWAGEFACTController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/T_SEWAGEFACT
            [EnableQuery]
            public IQueryable<T_SEWAGEFACT> GetT_SEWAGEFACT()
            {
                return db.T_SEWAGEFACT;
            }
    
            // GET: odata/T_SEWAGEFACT(5)
            [EnableQuery]
            public SingleResult<T_SEWAGEFACT> GetT_SEWAGEFACT([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.T_SEWAGEFACT.Where(w => w.OBJECTID == key));
            }
    
            // PUT: odata/T_SEWAGEFACT(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<T_SEWAGEFACT> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_SEWAGEFACT T_SEWAGEFACT = db.T_SEWAGEFACT.Find(key);
                if (T_SEWAGEFACT == null)
                {
                    return NotFound();
                }
    
                patch.Put(T_SEWAGEFACT);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_SEWAGEFACTExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_SEWAGEFACT);
            }
    
            // POST: odata/T_SEWAGEFACT
            public IHttpActionResult Post(T_SEWAGEFACT T_SEWAGEFACT)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.T_SEWAGEFACT.Add(T_SEWAGEFACT);
                db.SaveChanges();
    
                return Created(T_SEWAGEFACT);
            }
    
            // PATCH: odata/T_SEWAGEFACT(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<T_SEWAGEFACT> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_SEWAGEFACT T_SEWAGEFACT = db.T_SEWAGEFACT.Find(key);
                if (T_SEWAGEFACT == null)
                {
                    return NotFound();
                }
    
                patch.Patch(T_SEWAGEFACT);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_SEWAGEFACTExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_SEWAGEFACT);
            }
    
            // DELETE: odata/T_SEWAGEFACT(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                T_SEWAGEFACT T_SEWAGEFACT = db.T_SEWAGEFACT.Find(key);
                if (T_SEWAGEFACT == null)
                {
                    return NotFound();
                }
    
                db.T_SEWAGEFACT.Remove(T_SEWAGEFACT);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool T_SEWAGEFACTExists(decimal key)
            {
                return db.T_SEWAGEFACT.Count(e => e.OBJECTID == key) > 0;
            }
      
    }
}
