//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class T_WASEVS_R3Controller:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/T_WASEVS_R3
            [EnableQuery]
            public IQueryable<T_WASEVS_R3> GetT_WASEVS_R3()
            {
                return db.T_WASEVS_R3;
            }
    
            // GET: odata/T_WASEVS_R3(5)
            [EnableQuery]
            public SingleResult<T_WASEVS_R3> GetT_WASEVS_R3([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.T_WASEVS_R3.Where(w => w.N_ID == key));
            }
    
            // PUT: odata/T_WASEVS_R3(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<T_WASEVS_R3> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_WASEVS_R3 T_WASEVS_R3 = db.T_WASEVS_R3.Find(key);
                if (T_WASEVS_R3 == null)
                {
                    return NotFound();
                }
    
                patch.Put(T_WASEVS_R3);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_WASEVS_R3Exists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_WASEVS_R3);
            }
    
            // POST: odata/T_WASEVS_R3
            public IHttpActionResult Post(T_WASEVS_R3 T_WASEVS_R3)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.T_WASEVS_R3.Add(T_WASEVS_R3);
                db.SaveChanges();
    
                return Created(T_WASEVS_R3);
            }
    
            // PATCH: odata/T_WASEVS_R3(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<T_WASEVS_R3> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                T_WASEVS_R3 T_WASEVS_R3 = db.T_WASEVS_R3.Find(key);
                if (T_WASEVS_R3 == null)
                {
                    return NotFound();
                }
    
                patch.Patch(T_WASEVS_R3);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!T_WASEVS_R3Exists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(T_WASEVS_R3);
            }
    
            // DELETE: odata/T_WASEVS_R3(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                T_WASEVS_R3 T_WASEVS_R3 = db.T_WASEVS_R3.Find(key);
                if (T_WASEVS_R3 == null)
                {
                    return NotFound();
                }
    
                db.T_WASEVS_R3.Remove(T_WASEVS_R3);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool T_WASEVS_R3Exists(decimal key)
            {
                return db.T_WASEVS_R3.Count(e => e.N_ID == key) > 0;
            }
      
    }
}
