//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class TB_DATAINTEGRITYController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/TB_DATAINTEGRITY
            [EnableQuery]
            public IQueryable<TB_DATAINTEGRITY> GetTB_DATAINTEGRITY()
            {
                return db.TB_DATAINTEGRITY;
            }
    
            // GET: odata/TB_DATAINTEGRITY(5)
            [EnableQuery]
            public SingleResult<TB_DATAINTEGRITY> GetTB_DATAINTEGRITY([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.TB_DATAINTEGRITY.Where(w => w.SID == key));
            }
    
            // PUT: odata/TB_DATAINTEGRITY(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<TB_DATAINTEGRITY> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_DATAINTEGRITY TB_DATAINTEGRITY = db.TB_DATAINTEGRITY.Find(key);
                if (TB_DATAINTEGRITY == null)
                {
                    return NotFound();
                }
    
                patch.Put(TB_DATAINTEGRITY);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_DATAINTEGRITYExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_DATAINTEGRITY);
            }
    
            // POST: odata/TB_DATAINTEGRITY
            public IHttpActionResult Post(TB_DATAINTEGRITY TB_DATAINTEGRITY)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.TB_DATAINTEGRITY.Add(TB_DATAINTEGRITY);
                db.SaveChanges();
    
                return Created(TB_DATAINTEGRITY);
            }
    
            // PATCH: odata/TB_DATAINTEGRITY(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<TB_DATAINTEGRITY> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_DATAINTEGRITY TB_DATAINTEGRITY = db.TB_DATAINTEGRITY.Find(key);
                if (TB_DATAINTEGRITY == null)
                {
                    return NotFound();
                }
    
                patch.Patch(TB_DATAINTEGRITY);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_DATAINTEGRITYExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_DATAINTEGRITY);
            }
    
            // DELETE: odata/TB_DATAINTEGRITY(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                TB_DATAINTEGRITY TB_DATAINTEGRITY = db.TB_DATAINTEGRITY.Find(key);
                if (TB_DATAINTEGRITY == null)
                {
                    return NotFound();
                }
    
                db.TB_DATAINTEGRITY.Remove(TB_DATAINTEGRITY);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool TB_DATAINTEGRITYExists(decimal key)
            {
                return db.TB_DATAINTEGRITY.Count(e => e.SID == key) > 0;
            }
      
    }
}
