//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class TB_DATADIRECTORYController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/TB_DATADIRECTORY
            [EnableQuery]
            public IQueryable<TB_DATADIRECTORY> GetTB_DATADIRECTORY()
            {
                return db.TB_DATADIRECTORY;
            }
    
            // GET: odata/TB_DATADIRECTORY(5)
            [EnableQuery]
            public SingleResult<TB_DATADIRECTORY> GetTB_DATADIRECTORY([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.TB_DATADIRECTORY.Where(w => w.ID == key));
            }
    
            // PUT: odata/TB_DATADIRECTORY(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<TB_DATADIRECTORY> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_DATADIRECTORY TB_DATADIRECTORY = db.TB_DATADIRECTORY.Find(key);
                if (TB_DATADIRECTORY == null)
                {
                    return NotFound();
                }
    
                patch.Put(TB_DATADIRECTORY);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_DATADIRECTORYExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_DATADIRECTORY);
            }
    
            // POST: odata/TB_DATADIRECTORY
            public IHttpActionResult Post(TB_DATADIRECTORY TB_DATADIRECTORY)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.TB_DATADIRECTORY.Add(TB_DATADIRECTORY);
                db.SaveChanges();
    
                return Created(TB_DATADIRECTORY);
            }
    
            // PATCH: odata/TB_DATADIRECTORY(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<TB_DATADIRECTORY> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_DATADIRECTORY TB_DATADIRECTORY = db.TB_DATADIRECTORY.Find(key);
                if (TB_DATADIRECTORY == null)
                {
                    return NotFound();
                }
    
                patch.Patch(TB_DATADIRECTORY);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_DATADIRECTORYExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_DATADIRECTORY);
            }
    
            // DELETE: odata/TB_DATADIRECTORY(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                TB_DATADIRECTORY TB_DATADIRECTORY = db.TB_DATADIRECTORY.Find(key);
                if (TB_DATADIRECTORY == null)
                {
                    return NotFound();
                }
    
                db.TB_DATADIRECTORY.Remove(TB_DATADIRECTORY);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool TB_DATADIRECTORYExists(decimal key)
            {
                return db.TB_DATADIRECTORY.Count(e => e.ID == key) > 0;
            }
      
    }
}
