//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class TB_DICTIANORYController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/TB_DICTIANORY
            [EnableQuery]
            public IQueryable<TB_DICTIANORY> GetTB_DICTIANORY()
            {
                return db.TB_DICTIANORY;
            }
    
            // GET: odata/TB_DICTIANORY(5)
            [EnableQuery]
            public SingleResult<TB_DICTIANORY> GetTB_DICTIANORY([FromODataUri] string key)
            {
                return SingleResult.Create(db.TB_DICTIANORY.Where(w => w.N_ID == key));
            }
    
            // PUT: odata/TB_DICTIANORY(5)
            public IHttpActionResult Put([FromODataUri] string key, Delta<TB_DICTIANORY> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_DICTIANORY TB_DICTIANORY = db.TB_DICTIANORY.Find(key);
                if (TB_DICTIANORY == null)
                {
                    return NotFound();
                }
    
                patch.Put(TB_DICTIANORY);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_DICTIANORYExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_DICTIANORY);
            }
    
            // POST: odata/TB_DICTIANORY
            public IHttpActionResult Post(TB_DICTIANORY TB_DICTIANORY)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.TB_DICTIANORY.Add(TB_DICTIANORY);
                db.SaveChanges();
    
                return Created(TB_DICTIANORY);
            }
    
            // PATCH: odata/TB_DICTIANORY(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] string key, Delta<TB_DICTIANORY> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_DICTIANORY TB_DICTIANORY = db.TB_DICTIANORY.Find(key);
                if (TB_DICTIANORY == null)
                {
                    return NotFound();
                }
    
                patch.Patch(TB_DICTIANORY);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_DICTIANORYExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_DICTIANORY);
            }
    
            // DELETE: odata/TB_DICTIANORY(5)
            public IHttpActionResult Delete([FromODataUri] string key)
            {
                TB_DICTIANORY TB_DICTIANORY = db.TB_DICTIANORY.Find(key);
                if (TB_DICTIANORY == null)
                {
                    return NotFound();
                }
    
                db.TB_DICTIANORY.Remove(TB_DICTIANORY);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool TB_DICTIANORYExists(string key)
            {
                return db.TB_DICTIANORY.Count(e => e.N_ID == key) > 0;
            }
      
    }
}
