//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class TB_ITEMController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/TB_ITEM
            [EnableQuery]
            public IQueryable<TB_ITEM> GetTB_ITEM()
            {
                return db.TB_ITEM;
            }
    
            // GET: odata/TB_ITEM(5)
            [EnableQuery]
            public SingleResult<TB_ITEM> GetTB_ITEM([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.TB_ITEM.Where(w => w.N_ITEMID == key));
            }
    
            // PUT: odata/TB_ITEM(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<TB_ITEM> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_ITEM TB_ITEM = db.TB_ITEM.Find(key);
                if (TB_ITEM == null)
                {
                    return NotFound();
                }
    
                patch.Put(TB_ITEM);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_ITEMExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_ITEM);
            }
    
            // POST: odata/TB_ITEM
            public IHttpActionResult Post(TB_ITEM TB_ITEM)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.TB_ITEM.Add(TB_ITEM);
                db.SaveChanges();
    
                return Created(TB_ITEM);
            }
    
            // PATCH: odata/TB_ITEM(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<TB_ITEM> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_ITEM TB_ITEM = db.TB_ITEM.Find(key);
                if (TB_ITEM == null)
                {
                    return NotFound();
                }
    
                patch.Patch(TB_ITEM);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_ITEMExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_ITEM);
            }
    
            // DELETE: odata/TB_ITEM(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                TB_ITEM TB_ITEM = db.TB_ITEM.Find(key);
                if (TB_ITEM == null)
                {
                    return NotFound();
                }
    
                db.TB_ITEM.Remove(TB_ITEM);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool TB_ITEMExists(decimal key)
            {
                return db.TB_ITEM.Count(e => e.N_ITEMID == key) > 0;
            }
      
    }
}
