//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class TB_TRANSATTACHController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/TB_TRANSATTACH
            [EnableQuery]
            public IQueryable<TB_TRANSATTACH> GetTB_TRANSATTACH()
            {
                return db.TB_TRANSATTACH;
            }
    
            // GET: odata/TB_TRANSATTACH(5)
            [EnableQuery]
            public SingleResult<TB_TRANSATTACH> GetTB_TRANSATTACH([FromODataUri] string key)
            {
                return SingleResult.Create(db.TB_TRANSATTACH.Where(w => w.ID == key));
            }
    
            // PUT: odata/TB_TRANSATTACH(5)
            public IHttpActionResult Put([FromODataUri] string key, Delta<TB_TRANSATTACH> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_TRANSATTACH TB_TRANSATTACH = db.TB_TRANSATTACH.Find(key);
                if (TB_TRANSATTACH == null)
                {
                    return NotFound();
                }
    
                patch.Put(TB_TRANSATTACH);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_TRANSATTACHExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_TRANSATTACH);
            }
    
            // POST: odata/TB_TRANSATTACH
            public IHttpActionResult Post(TB_TRANSATTACH TB_TRANSATTACH)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.TB_TRANSATTACH.Add(TB_TRANSATTACH);
                db.SaveChanges();
    
                return Created(TB_TRANSATTACH);
            }
    
            // PATCH: odata/TB_TRANSATTACH(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] string key, Delta<TB_TRANSATTACH> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_TRANSATTACH TB_TRANSATTACH = db.TB_TRANSATTACH.Find(key);
                if (TB_TRANSATTACH == null)
                {
                    return NotFound();
                }
    
                patch.Patch(TB_TRANSATTACH);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_TRANSATTACHExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_TRANSATTACH);
            }
    
            // DELETE: odata/TB_TRANSATTACH(5)
            public IHttpActionResult Delete([FromODataUri] string key)
            {
                TB_TRANSATTACH TB_TRANSATTACH = db.TB_TRANSATTACH.Find(key);
                if (TB_TRANSATTACH == null)
                {
                    return NotFound();
                }
    
                db.TB_TRANSATTACH.Remove(TB_TRANSATTACH);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool TB_TRANSATTACHExists(string key)
            {
                return db.TB_TRANSATTACH.Count(e => e.ID == key) > 0;
            }
      
    }
}
