//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class TB_YULIANG_DAYController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/TB_YULIANG_DAY
            [EnableQuery]
            public IQueryable<TB_YULIANG_DAY> GetTB_YULIANG_DAY()
            {
                return db.TB_YULIANG_DAY;
            }
    
            // GET: odata/TB_YULIANG_DAY(5)
            [EnableQuery]
            public SingleResult<TB_YULIANG_DAY> GetTB_YULIANG_DAY([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.TB_YULIANG_DAY.Where(w => w.SID == key));
            }
    
            // PUT: odata/TB_YULIANG_DAY(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<TB_YULIANG_DAY> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_YULIANG_DAY TB_YULIANG_DAY = db.TB_YULIANG_DAY.Find(key);
                if (TB_YULIANG_DAY == null)
                {
                    return NotFound();
                }
    
                patch.Put(TB_YULIANG_DAY);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_YULIANG_DAYExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_YULIANG_DAY);
            }
    
            // POST: odata/TB_YULIANG_DAY
            public IHttpActionResult Post(TB_YULIANG_DAY TB_YULIANG_DAY)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.TB_YULIANG_DAY.Add(TB_YULIANG_DAY);
                db.SaveChanges();
    
                return Created(TB_YULIANG_DAY);
            }
    
            // PATCH: odata/TB_YULIANG_DAY(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<TB_YULIANG_DAY> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                TB_YULIANG_DAY TB_YULIANG_DAY = db.TB_YULIANG_DAY.Find(key);
                if (TB_YULIANG_DAY == null)
                {
                    return NotFound();
                }
    
                patch.Patch(TB_YULIANG_DAY);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TB_YULIANG_DAYExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(TB_YULIANG_DAY);
            }
    
            // DELETE: odata/TB_YULIANG_DAY(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                TB_YULIANG_DAY TB_YULIANG_DAY = db.TB_YULIANG_DAY.Find(key);
                if (TB_YULIANG_DAY == null)
                {
                    return NotFound();
                }
    
                db.TB_YULIANG_DAY.Remove(TB_YULIANG_DAY);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool TB_YULIANG_DAYExists(decimal key)
            {
                return db.TB_YULIANG_DAY.Count(e => e.SID == key) > 0;
            }
      
    }
}
