//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class V_WQAMD_RController:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/V_WQAMD_R
            [EnableQuery]
            public IQueryable<V_WQAMD_R> GetV_WQAMD_R()
            {
                return db.V_WQAMD_R;
            }
    
            // GET: odata/V_WQAMD_R(5)
            [EnableQuery]
            public SingleResult<V_WQAMD_R> GetV_WQAMD_R([FromODataUri] decimal key)
            {
                return SingleResult.Create(db.V_WQAMD_R.Where(w => w.N_ID == key));
            }
    
            // PUT: odata/V_WQAMD_R(5)
            public IHttpActionResult Put([FromODataUri] decimal key, Delta<V_WQAMD_R> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                V_WQAMD_R V_WQAMD_R = db.V_WQAMD_R.Find(key);
                if (V_WQAMD_R == null)
                {
                    return NotFound();
                }
    
                patch.Put(V_WQAMD_R);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!V_WQAMD_RExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(V_WQAMD_R);
            }
    
            // POST: odata/V_WQAMD_R
            public IHttpActionResult Post(V_WQAMD_R V_WQAMD_R)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.V_WQAMD_R.Add(V_WQAMD_R);
                db.SaveChanges();
    
                return Created(V_WQAMD_R);
            }
    
            // PATCH: odata/V_WQAMD_R(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] decimal key, Delta<V_WQAMD_R> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                V_WQAMD_R V_WQAMD_R = db.V_WQAMD_R.Find(key);
                if (V_WQAMD_R == null)
                {
                    return NotFound();
                }
    
                patch.Patch(V_WQAMD_R);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!V_WQAMD_RExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(V_WQAMD_R);
            }
    
            // DELETE: odata/V_WQAMD_R(5)
            public IHttpActionResult Delete([FromODataUri] decimal key)
            {
                V_WQAMD_R V_WQAMD_R = db.V_WQAMD_R.Find(key);
                if (V_WQAMD_R == null)
                {
                    return NotFound();
                }
    
                db.V_WQAMD_R.Remove(V_WQAMD_R);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool V_WQAMD_RExists(decimal key)
            {
                return db.V_WQAMD_R.Count(e => e.N_ID == key) > 0;
            }
      
    }
}
