//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExampleForOracle.Models;
    public partial class 水闸Controller:ODataController
    {
            private SJZXEntities db = new SJZXEntities();
    
            // GET: odata/水闸
            [EnableQuery]
            public IQueryable<水闸> Get水闸()
            {
                return db.水闸;
            }
    
            // GET: odata/水闸(5)
            [EnableQuery]
            public SingleResult<水闸> Get水闸([FromODataUri] string key)
            {
                return SingleResult.Create(db.水闸.Where(w => w.S_SLUICE_ID == key));
            }
    
            // PUT: odata/水闸(5)
            public IHttpActionResult Put([FromODataUri] string key, Delta<水闸> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                水闸 水闸 = db.水闸.Find(key);
                if (水闸 == null)
                {
                    return NotFound();
                }
    
                patch.Put(水闸);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!水闸Exists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(水闸);
            }
    
            // POST: odata/水闸
            public IHttpActionResult Post(水闸 水闸)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.水闸.Add(水闸);
                db.SaveChanges();
    
                return Created(水闸);
            }
    
            // PATCH: odata/水闸(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] string key, Delta<水闸> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                水闸 水闸 = db.水闸.Find(key);
                if (水闸 == null)
                {
                    return NotFound();
                }
    
                patch.Patch(水闸);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!水闸Exists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(水闸);
            }
    
            // DELETE: odata/水闸(5)
            public IHttpActionResult Delete([FromODataUri] string key)
            {
                水闸 水闸 = db.水闸.Find(key);
                if (水闸 == null)
                {
                    return NotFound();
                }
    
                db.水闸.Remove(水闸);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool 水闸Exists(string key)
            {
                return db.水闸.Count(e => e.S_SLUICE_ID == key) > 0;
            }
      
    }
}
