//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE_USAGE
    {
        public string US_STATE { get; set; }
        public Nullable<int> POLARITY { get; set; }
        public Nullable<decimal> USAGE_AVG { get; set; }
    }
}
