//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ADMIN_LICENSE
    {
        public string S_ID { get; set; }
        public string S_BH { get; set; }
        public string S_PSXMMC { get; set; }
        public string S_PSXMDZ { get; set; }
        public string S_SQDW { get; set; }
        public string S_DZ { get; set; }
        public Nullable<int> N_YB { get; set; }
        public string S_LXR { get; set; }
        public string S_LXFS { get; set; }
        public Nullable<System.DateTime> T_SDRQ { get; set; }
        public Nullable<System.DateTime> T_SLRQ { get; set; }
        public Nullable<System.DateTime> T_BJSJ { get; set; }
        public Nullable<System.DateTime> T_XKQX { get; set; }
        public string S_SLH { get; set; }
        public string S_ZH { get; set; }
        public string S_STATUS { get; set; }
    }
}
