//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMMUNITY
    {
        public decimal OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public Nullable<decimal> N_TOWNID { get; set; }
        public string S_TOWNNAME { get; set; }
        public string S_COMMUNITYNAME { get; set; }
        public Nullable<decimal> N_AREA { get; set; }
        public Nullable<short> N_2009REBULID { get; set; }
        public Nullable<short> N_NOWSTATUS { get; set; }
        public Nullable<short> N_2017REBULID { get; set; }
        public Nullable<short> N_BEAUTIFULHOME { get; set; }
        public Nullable<short> N_NOPLAN { get; set; }
        public Nullable<short> N_ISMIXING { get; set; }
        public string S_REMARK { get; set; }
    }
}
