//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DRAINUSEROLD
    {
        public decimal OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public string S_DRAINC_ID { get; set; }
        public string S_DRAINC_NAME { get; set; }
        public string S_DRAINC_GB_ID { get; set; }
        public string S_DRAINC_LICENCE_ID { get; set; }
        public string S_SYS_ID { get; set; }
        public string S_FACT_ID { get; set; }
        public Nullable<short> N_DRAINC_TYPE_LIC { get; set; }
        public Nullable<System.DateTime> T_DRAINC_DATE_LIC { get; set; }
        public Nullable<System.DateTime> T_PERMITBEGINDATE { get; set; }
        public Nullable<System.DateTime> T_PERMITENDDATE { get; set; }
        public string S_DRAINC_ADD { get; set; }
        public string S_DRAINC_PROJ_NAME { get; set; }
        public string S_DRAINC_PROJ__ADD { get; set; }
        public Nullable<short> N_DRAINC_PROJ_TYPE { get; set; }
        public string S_DRAINC_LEGAL_PSN { get; set; }
        public string S_DRAINC_PHONE { get; set; }
        public string S_DRAINC_POST_CODE { get; set; }
        public Nullable<decimal> N_DRAINC_WATER_SUM { get; set; }
        public Nullable<decimal> N_DRAINC_PROVIDE_DAY { get; set; }
        public Nullable<decimal> N_DRAINC_DRAIN_SUM { get; set; }
        public Nullable<decimal> N_DRAINC_SEWAGE_INDU { get; set; }
        public Nullable<decimal> N_DRAINC_SEWAGE_LIVE { get; set; }
        public string S_DRAINC_POLLUTANT { get; set; }
        public Nullable<short> N_DRAINC_TYPE_TREAT { get; set; }
        public string S_DRAINC_METHOD_TREAT { get; set; }
        public Nullable<short> N_DRAINC_NUM_OUT { get; set; }
        public string S_DRAINC_PLAN { get; set; }
        public string S_MAPSHEETID { get; set; }
        public Nullable<System.DateTime> T_BUILDDATE { get; set; }
        public Nullable<short> N_BUILDYEAR { get; set; }
        public string S_IN_COM { get; set; }
        public Nullable<System.DateTime> T_IN_DATE { get; set; }
        public string S_IN_USE { get; set; }
        public Nullable<System.DateTime> N_VERSIONID { get; set; }
        public string S_REMARK { get; set; }
        public Nullable<short> N_KEY_ID { get; set; }
        public string S_USERID { get; set; }
        public string S_DRAINC_LOC_OUT { get; set; }
        public Nullable<short> N_DRAINC_DIM_OUT { get; set; }
        public string S_DRAI_PIPE_ID { get; set; }
        public string S_DRAINC_MANHOLE { get; set; }
        public Nullable<short> N_ISUSE { get; set; }
    }
}
