//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FLOODWALL_DW
    {
        public decimal OBJECTID { get; set; }
        public string S_WALL_ID { get; set; }
        public string S_NAME { get; set; }
        public string S_RIV_ID { get; set; }
        public string S_SIDE { get; set; }
        public Nullable<decimal> N_STAKE_PLAM { get; set; }
        public Nullable<decimal> N_STAKE_PULL { get; set; }
        public Nullable<decimal> N_SCENE_WALL { get; set; }
        public Nullable<decimal> N_ELSE_FORM { get; set; }
        public Nullable<decimal> N_WIDTH_PEAK { get; set; }
        public Nullable<decimal> N_TIDE_LOCKS { get; set; }
        public Nullable<decimal> N_OUTLET_NUM { get; set; }
        public string S_CORP_MTN { get; set; }
        public string S_LEGAL_PSN { get; set; }
        public string S_ADDRESS { get; set; }
        public string S_PHONE { get; set; }
        public Nullable<decimal> N_CONDITION { get; set; }
        public string S_REMARK { get; set; }
        public string S_DIST_ID { get; set; }
        public string S_IN_COM { get; set; }
        public Nullable<System.DateTime> T_IN_DATE { get; set; }
        public string S_DMH { get; set; }
        public Nullable<decimal> N_B_M_X { get; set; }
        public Nullable<decimal> N_E_M_X { get; set; }
        public Nullable<decimal> N_B_M_Y { get; set; }
        public Nullable<decimal> N_E_M_Y { get; set; }
        public string S_PIC { get; set; }
        public Nullable<decimal> N_QHCDZK { get; set; }
        public Nullable<decimal> N_JGXS { get; set; }
        public string S_SJDW { get; set; }
        public string S_ADSX { get; set; }
        public string S_SYQK { get; set; }
        public string S_ZYA { get; set; }
        public string S_MILESTONE_B { get; set; }
        public string S_MILESTONE_E { get; set; }
        public string S_REACHFEATURE { get; set; }
        public Nullable<decimal> N_REACHLENGTH { get; set; }
        public Nullable<decimal> N_CONCRETE_WALL { get; set; }
        public string S_ALTITUDE_PEAK { get; set; }
        public string S_ALTITUDE_OWAL { get; set; }
        public string S_ALTITUDE_IWAL { get; set; }
        public Nullable<decimal> N_FLASH_LOCKS { get; set; }
        public string S_MERGE_ID { get; set; }
        public string S_WENTI { get; set; }
        public string S_RIV_ID_CH { get; set; }
        public string S_CASEID { get; set; }
        public Nullable<decimal> N_CURRENT_STATE { get; set; }
        public string S_VERSION { get; set; }
        public string S_PMT { get; set; }
        public Nullable<short> N_ISSURE { get; set; }
        public Nullable<short> N_SHIYI { get; set; }
        public Nullable<decimal> N_SHAPE_LENGTH { get; set; }
        public string S_FILEID { get; set; }
        public Nullable<decimal> N_ISUSE { get; set; }
        public string S_XTBM { get; set; }
    }
}
