//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FXCZM
    {
        public decimal OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public string S_OUTLET_ID { get; set; }
        public string S_ANDUAN_MNG { get; set; }
        public Nullable<decimal> N_CITY_X { get; set; }
        public Nullable<decimal> N_CITY_Y { get; set; }
        public string S_WALL_ID { get; set; }
        public string S_DIST_ID { get; set; }
        public string S_METHOD_OUT { get; set; }
        public string S_TYPE_DIRT { get; set; }
        public Nullable<decimal> N_DRAIN_SUM { get; set; }
        public string S_MILES_CODE { get; set; }
        public string S_DIAMETER { get; set; }
        public Nullable<decimal> N_BOTTOM { get; set; }
        public Nullable<System.DateTime> T_SET_DATE { get; set; }
        public string S_SET_REASON { get; set; }
        public string S_CORP_USE { get; set; }
        public string S_CORP_TYPE { get; set; }
        public string S_CONDITION { get; set; }
        public string S_COM_MNG { get; set; }
        public string S_REMARK { get; set; }
        public string S_SIDE { get; set; }
        public string S_POINT { get; set; }
        public string S_RIVER_ID { get; set; }
        public string S_IN_COM { get; set; }
        public Nullable<System.DateTime> T_IN_DATE { get; set; }
        public Nullable<decimal> N_BB { get; set; }
        public string S_RIVER_CH { get; set; }
        public Nullable<decimal> N_CURRENT_STATE { get; set; }
        public string S_VERSION { get; set; }
        public Nullable<short> N_ISUSE { get; set; }
    }
}
