//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FXTD2
    {
        public decimal OBJECTID { get; set; }
        public string S_PATH_ID { get; set; }
        public string S_PATH_NAME { get; set; }
        public string S_RIV_ID { get; set; }
        public string S_PATH_TYPE_ROAD { get; set; }
        public Nullable<decimal> N_PATH_LENGTH { get; set; }
        public Nullable<decimal> N_PATH_ALT_ROAD { get; set; }
        public string S_PATH_MILES_B { get; set; }
        public string S_PATH_MILES_E { get; set; }
        public Nullable<short> N_PATH_CAPA_DSN { get; set; }
        public Nullable<decimal> N_PATH_WIDTH_ROAD { get; set; }
        public Nullable<short> N_DIST_ID { get; set; }
        public string S_PATH_COM_MNG { get; set; }
        public string S_PATH_REMARK { get; set; }
        public Nullable<decimal> S_CURRENT_STATE { get; set; }
        public string S_ADSX { get; set; }
        public string S_LMJG { get; set; }
        public string S_LJZLM { get; set; }
        public string S_GLDFID { get; set; }
        public string S_QX { get; set; }
        public string S_SSHD { get; set; }
        public string S_ANBIE { get; set; }
        public string S_SHAXDW { get; set; }
        public string S_QZH { get; set; }
        public string S_ZZH { get; set; }
        public string S_VERSION { get; set; }
        public Nullable<decimal> N_SHAPE_LENGTH { get; set; }
        public Nullable<decimal> N_ISUSE { get; set; }
        public string S_XTBM { get; set; }
    }
}
