//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FXZM
    {
        public decimal OBJECTID { get; set; }
        public string S_ID { get; set; }
        public string S_NAME { get; set; }
        public Nullable<decimal> N_X { get; set; }
        public Nullable<decimal> N_Y { get; set; }
        public string S_WALL_ID { get; set; }
        public string S_DOOR_PLACE { get; set; }
        public string S_DOOR_TYPE { get; set; }
        public Nullable<decimal> N_DOOR_WIDTH { get; set; }
        public Nullable<decimal> N_DOOR_BOTTOM { get; set; }
        public string S_REMARK { get; set; }
        public Nullable<decimal> N_DOOR_ALTITUDE { get; set; }
        public string S_SIDE { get; set; }
        public string S_POINT { get; set; }
        public string S_RIV_ID { get; set; }
        public string S_COM_MNG { get; set; }
        public Nullable<decimal> N_UP_COORD_X { get; set; }
        public Nullable<decimal> N_UP_COORD_Y { get; set; }
        public Nullable<decimal> N_DOWN_COORD_X { get; set; }
        public Nullable<decimal> N_DOWN_COORD_Y { get; set; }
        public string S_IN_COM { get; set; }
        public Nullable<System.DateTime> T_IN_DATE { get; set; }
        public Nullable<decimal> N_BB { get; set; }
        public string S_RIV_CH { get; set; }
        public string S_DISTRICT { get; set; }
        public string S_VERSION { get; set; }
        public Nullable<decimal> N_ISUSE { get; set; }
        public string S_XTBM { get; set; }
    }
}
