//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FXQLCZ
    {
        public decimal OBJECTID { get; set; }
        public string S_SHAPE { get; set; }
        public string S_MILES_RIV_ID { get; set; }
        public string S_CODE { get; set; }
        public string S_RIV_ID { get; set; }
        public string S_WALL_ID { get; set; }
        public Nullable<decimal> N_SIDE { get; set; }
        public string S_DISTANCE { get; set; }
        public Nullable<decimal> N_COORD_X { get; set; }
        public Nullable<decimal> N_COORD_Y { get; set; }
        public string S_PICTURE { get; set; }
        public string S_REMARK { get; set; }
        public string S_POINT { get; set; }
        public string S_IN_COM { get; set; }
        public Nullable<System.DateTime> T_IN_DATE { get; set; }
        public Nullable<decimal> N_BB { get; set; }
        public Nullable<decimal> N_WGS84_X { get; set; }
        public Nullable<decimal> N_WGS84_Y { get; set; }
        public Nullable<decimal> N_CURRENT_STATE { get; set; }
        public string S_VERSION { get; set; }
        public Nullable<decimal> N_ISUSE { get; set; }
        public string S_XTBM { get; set; }
    }
}
