//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GJSWZOLD
    {
        public decimal OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public string S_RECON_ID { get; set; }
        public string S_RECON_NAME { get; set; }
        public string S_HNET { get; set; }
        public string S_RINM_ID { get; set; }
        public Nullable<short> N_RECON_STTPCD { get; set; }
        public string S_RECON_OBITCD { get; set; }
        public string S_RECON_ADDRESS { get; set; }
        public string S_RECON_ESLO { get; set; }
        public string S_RECON_NTLA { get; set; }
        public Nullable<System.DateTime> T_RECON_TIME { get; set; }
        public Nullable<decimal> N_RECON_TDZ { get; set; }
        public Nullable<decimal> N_RECON_Q { get; set; }
        public Nullable<decimal> N_RECON_R { get; set; }
        public Nullable<decimal> N_RECON_L { get; set; }
        public Nullable<decimal> N_RECON_CS { get; set; }
        public Nullable<short> N_RECON_WPWR { get; set; }
        public string S_RECON_WDRT { get; set; }
        public Nullable<decimal> N_RECON_WAVE { get; set; }
        public Nullable<System.DateTime> T_RECON_ESSTYM { get; set; }
        public Nullable<System.DateTime> T_RECON_WSTTYM { get; set; }
        public string S_RECON_REMARK { get; set; }
        public Nullable<short> N_SENID { get; set; }
        public string S_DIST_ID { get; set; }
        public Nullable<decimal> N_COORD_X { get; set; }
        public Nullable<decimal> N_COORD_Y { get; set; }
        public string S_COM_MNG { get; set; }
        public string S_IN_COM { get; set; }
        public Nullable<System.DateTime> T_IN_DATE { get; set; }
        public Nullable<short> N_ISUSE { get; set; }
    }
}
