//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GPBZ
    {
        public decimal OBJECTID_12 { get; set; }
        public Nullable<decimal> OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public string S_IRRI_DRAI_PUMP_NAME { get; set; }
        public string S_IRRI_DRAI_PUMP_ID { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP_EASTX { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP_EASTLONGM { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP_EASTLONGS { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP_NORTHY { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP_NORTHLATM { get; set; }
        public string N_IRRI_DRAI_PUMP_NORTHLATS { get; set; }
        public string S_DIST_NAME { get; set; }
        public string N_DIST_ID { get; set; }
        public string S_TOWN_NAME { get; set; }
        public string S_VILLAGE { get; set; }
        public string S_WATERRESOURCES_NAME { get; set; }
        public string S_WATERRESOURCES_ID { get; set; }
        public string S_RIVER_NAME { get; set; }
        public string S_RIVER_ID { get; set; }
        public string S_POLDER_NAME { get; set; }
        public string S_POLDER_ID { get; set; }
        public string S_EWCA_ID { get; set; }
        public string S_WATERPROJECT { get; set; }
        public string S_WATERPROJECTREGION { get; set; }
        public string S_ALONGRIVER { get; set; }
        public string N_IRRI_DRAI_PUMP_TYPE { get; set; }
        public string S_ISPUMPPROJECT { get; set; }
        public string S_ISSPRINGWATERPROJECT { get; set; }
        public string S_PROJECTCONSTRUCTION { get; set; }
        public Nullable<System.DateTime> T_IRRI_DRAI_PUMP_TIME_BLD { get; set; }
        public Nullable<System.DateTime> T_IRRI_DRAI_PUMP_TIME_RBD { get; set; }
        public string S_ENGINEERINGTASK { get; set; }
        public string S_ENGINEERINGGRADE { get; set; }
        public string S_BUILDINGGRADE { get; set; }
        public string S_KANGZHENGSFLD { get; set; }
        public Nullable<decimal> N_INSTALLEDFLOW { get; set; }
        public Nullable<decimal> N_INSTALLEDPOWER { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP_DSNLIFT { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP_DSNFLOW { get; set; }
        public Nullable<short> N_IRRI_DRAI_NUM_PUMP { get; set; }
        public string S_IRRI_DRAI_MOD_PUMP { get; set; }
        public string S_IRRI_DRAI_TYPE_PUMP { get; set; }
        public string S_IRRI_DRAI_PUMP_MNG_NAME { get; set; }
        public string S_IRRI_DRAI_PUMP_MNG_ID { get; set; }
        public string S_IRRI_DRAI_PUMP_CENTRALIZED { get; set; }
        public string S_ISDELIMIT { get; set; }
        public string S_ISRIGHT { get; set; }
        public string S_PREPARER { get; set; }
        public string S_PHONE { get; set; }
        public Nullable<System.DateTime> T_DATETIME { get; set; }
        public string S_CHECKER { get; set; }
        public string S_EXAMINER { get; set; }
        public string S_REPORTSTATUS { get; set; }
        public string S_IN_COM { get; set; }
        public string S_IRRI_DRAI_PUMP_LOCATION { get; set; }
        public Nullable<decimal> N_AREA_IRRI { get; set; }
        public Nullable<decimal> N_AREA_CDRAI { get; set; }
        public Nullable<decimal> N_AREA_NDRAI { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_NOMIFLOW_PUMP { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_DSNFLOW_PUMP { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_NOMILIFT_PUMP { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_NOMIEFFE_PUMP { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP_CAPA_MOTOR { get; set; }
        public Nullable<short> N_IRRI_DRAI_PUMP_NUM_MOTOR { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP__FUND_STATE { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP__FUND_SELF { get; set; }
        public Nullable<decimal> N_IRRI_DRAI_PUMP__DRAINMOD { get; set; }
        public string S_IRRI_DRAI_PUMP__PICTURE { get; set; }
        public string S_IRRI_DRAI_PUMP__REMARK { get; set; }
        public Nullable<short> N_ISUSE { get; set; }
        public Nullable<short> N_TOWNOWNED { get; set; }
    }
}
