//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JISHUI_R
    {
        public decimal N_ID { get; set; }
        public string S_NO { get; set; }
        public string S_SNAME { get; set; }
        public Nullable<System.DateTime> T_STIME { get; set; }
        public Nullable<decimal> N_VALUE { get; set; }
        public Nullable<decimal> S_C { get; set; }
        public Nullable<decimal> S_V { get; set; }
        public string S_WATERDESC { get; set; }
        public string S_CDESC { get; set; }
        public string S_VDESC { get; set; }
        public string S_TREND { get; set; }
        public string S_TYPE_R { get; set; }
        public string S_ISUSE { get; set; }
        public string S_CREATEUSER { get; set; }
        public Nullable<System.DateTime> T_CREATEDATE { get; set; }
        public string S_UPDATEUSER { get; set; }
        public Nullable<System.DateTime> T_UPDATEDATE { get; set; }
        public Nullable<System.DateTime> T_SYSTIME { get; set; }
        public Nullable<decimal> N_WATERVALUE { get; set; }
        public Nullable<decimal> N_CJZ { get; set; }
        public Nullable<decimal> N_LBJS { get; set; }
        public string S_CATEGORY { get; set; }
    }
}
