//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LAKE
    {
        public decimal OBJECTID { get; set; }
        public string S_LAKE_ID { get; set; }
        public string S_LAKE_NAME { get; set; }
        public string N_LAKE_GRADE { get; set; }
        public Nullable<short> N_DIST_ID { get; set; }
        public Nullable<decimal> N_LAKE_AREA { get; set; }
        public Nullable<short> N_LAKE_GRADE_NAV { get; set; }
        public Nullable<decimal> N_LAKE_RANGE { get; set; }
        public Nullable<decimal> N_LAKE_LEVEL_MAX { get; set; }
        public Nullable<decimal> N_LAKE_LEVEL_NOR { get; set; }
        public string S_RIV_CN_ID { get; set; }
        public Nullable<decimal> N_LAKE_CAPA_MAX { get; set; }
        public Nullable<decimal> N_LAKE_CAPA_NOR { get; set; }
        public Nullable<decimal> N_LAKE_CAPA_MIN { get; set; }
        public string S_LAKE_REMARK { get; set; }
        public string S_WATERCLASSIFY { get; set; }
        public string S_FLOWAREA_CONTROL { get; set; }
        public string S_RIVER_MANAGE { get; set; }
        public string S_WAVEMANAGE_LEVEL { get; set; }
        public string S_CROSSOVER_TYPE { get; set; }
        public Nullable<decimal> N_LENGTH { get; set; }
        public string S_LINECODE { get; set; }
        public string S_IS_ACROSSTOWN { get; set; }
        public string S_ADMINDIVISION { get; set; }
        public string S_PLOTGRADECLASSIFY { get; set; }
        public Nullable<decimal> N_SHAPE_LENGTH { get; set; }
        public Nullable<decimal> N_SHAPE_AREA { get; set; }
        public Nullable<short> N_ISUSE { get; set; }
        public string S_XTBM { get; set; }
        public string S_CLASSIFY { get; set; }
        public string S_FLOWTHROUGHTOWN { get; set; }
    }
}
