//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PSGD
    {
        public decimal OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public string S_DRAI_PIPE_ID { get; set; }
        public string S_SYS_ID { get; set; }
        public string S_SYS_NAME { get; set; }
        public string S_DRAI_PIPE_NAME_ROAD { get; set; }
        public Nullable<short> N_DRAI_PIPE_GRADE { get; set; }
        public Nullable<short> N_DRAI_PIPE_TYPE { get; set; }
        public Nullable<short> N_PRESSTYPE { get; set; }
        public string S_DRAI_PIPE_BROAD_NAME { get; set; }
        public string S_DRAI_PIPE_EROAD_NAME { get; set; }
        public Nullable<short> N_DRAI_PIPE_STYLE { get; set; }
        public Nullable<decimal> N_DRAI_PIPE_D1 { get; set; }
        public Nullable<decimal> N_DRAI_PIPE_D2 { get; set; }
        public Nullable<decimal> N_DRAI_PIPE_LENGTH { get; set; }
        public Nullable<short> N_DRAI_PIPE_MATERIAL { get; set; }
        public Nullable<decimal> N_DRAI_PIPE_ALT_BEG { get; set; }
        public Nullable<decimal> N_DRAI_PIPE_ALT_END { get; set; }
        public Nullable<decimal> N_DRAI_PIPE_PALT_BEG { get; set; }
        public Nullable<decimal> N_DRAI_PIPE_PALT_END { get; set; }
        public string S_B_MANHOLE_ID { get; set; }
        public string S_E_MANHOLE_ID { get; set; }
        public Nullable<decimal> N_DRAI_PIPE_MANHOLE_N { get; set; }
        public Nullable<decimal> N_DRAI_PIPE_STORMWELL_N { get; set; }
        public string S_DRAI_PIPE_INVERT { get; set; }
        public string S_DRAI_PIPE_STRUC { get; set; }
        public string S_DRAI_PIPE_HYDRA { get; set; }
        public Nullable<short> N_BURIESMETHOD { get; set; }
        public Nullable<short> N_BUILDSTATE { get; set; }
        public Nullable<short> N_RINGROAD { get; set; }
        public string S_DRAI_PIPE_COM_DSN { get; set; }
        public string S_DRAI_PIPE_COM_BUILD { get; set; }
        public string S_MANAGEUNIT { get; set; }
        public string S_DRAI_PIPE_COM_REP { get; set; }
        public Nullable<System.DateTime> D_FINISHDATE { get; set; }
        public Nullable<System.DateTime> D_RUNDATE { get; set; }
        public Nullable<System.DateTime> D_REBUILDDATE { get; set; }
        public string S_MAPSHEETID { get; set; }
        public Nullable<short> N_XIULIFANGFA { get; set; }
        public Nullable<short> N_GONGNENGZHUANGKUANG { get; set; }
        public Nullable<short> N_JIEKOUXINGSHI { get; set; }
        public Nullable<decimal> N_PODU { get; set; }
        public Nullable<short> N_DISTRICT { get; set; }
        public Nullable<short> N_TOWNOWNED { get; set; }
        public Nullable<short> N_THEIRSYSTEM { get; set; }
        public string S_JIANSHEDANWEI { get; set; }
        public string S_OBID { get; set; }
        public string S_OEID { get; set; }
        public Nullable<System.DateTime> D_BUILDDATE { get; set; }
        public Nullable<short> N_BUILDYEAR { get; set; }
        public string S_SHUJULAIYUAN { get; set; }
        public Nullable<decimal> N_DRAI_DEPTH_BEG { get; set; }
        public Nullable<decimal> N_DRAI_DEPTH_END { get; set; }
        public string S_IN_COM { get; set; }
        public Nullable<System.DateTime> T_IN_DATE { get; set; }
        public string S_IN_USE { get; set; }
        public Nullable<short> N_VERSIONID { get; set; }
        public string B_REMARK { get; set; }
        public Nullable<short> N_KEYID { get; set; }
        public string S_USERID { get; set; }
        public string S_B_MANHOLE_IDX { get; set; }
        public string S_E_MANHOLE_IDX { get; set; }
        public string S_B_X { get; set; }
        public string S_B_Y { get; set; }
        public string S_E_X { get; set; }
        public string S_E_Y { get; set; }
        public string S_B_XY { get; set; }
        public string S_E_XY { get; set; }
        public string S_GCFL { get; set; }
        public Nullable<short> N_GRADE { get; set; }
        public Nullable<short> N_ISUSE { get; set; }
    }
}
