//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PUMP_GRID_20170505
    {
        public decimal OBJECTID { get; set; }
        public string S_Pump_ID { get; set; }
        public string S_Grid_Type { get; set; }
        public string S_Grid_Kind { get; set; }
        public Nullable<decimal> N_Grid_Len { get; set; }
        public Nullable<decimal> N_Grid_Width { get; set; }
        public Nullable<decimal> N_Grid_PTBG { get; set; }
        public Nullable<decimal> N_Grid_Power { get; set; }
        public Nullable<decimal> N_Grid_Num { get; set; }
        public string S_Grid_Comp { get; set; }
        public Nullable<System.DateTime> D_Grid_Date { get; set; }
        public Nullable<decimal> N_Grid_Price { get; set; }
    }
}
