//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PUMP_GPD_INFO_20170505
    {
        public decimal OBJECTID { get; set; }
        public string S_Pump_ID { get; set; }
        public string N_Motor_Type { get; set; }
        public string S_Motor_Model { get; set; }
        public string S_Motor_Norm { get; set; }
        public Nullable<decimal> N_Motor_Count { get; set; }
    }
}
