//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RIVER_R
    {
        public decimal N_ID { get; set; }
        public string S_SCODE { get; set; }
        public string S_SNAME { get; set; }
        public Nullable<System.DateTime> T_TM { get; set; }
        public Nullable<decimal> N_Z { get; set; }
        public Nullable<decimal> N_Q { get; set; }
        public Nullable<decimal> N_XSA { get; set; }
        public Nullable<decimal> N_XSAVV { get; set; }
        public Nullable<decimal> N_XSMXV { get; set; }
        public string S_FLWCHRCD { get; set; }
        public string S_WPTN { get; set; }
        public string S_MSQMT { get; set; }
        public string S_MSAMT { get; set; }
        public string S_MSVMT { get; set; }
        public string S_CATEGORY { get; set; }
    }
}
