//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RTRPT_PUMP_KTMXBWSO2
    {
        public decimal N_ID { get; set; }
        public string S_BZBH { get; set; }
        public string S_PUMPNAME { get; set; }
        public string S_BJBH { get; set; }
        public string S_FJTYPE { get; set; }
        public Nullable<decimal> T_START { get; set; }
        public Nullable<decimal> N_KBSW { get; set; }
        public Nullable<decimal> T_END { get; set; }
        public Nullable<decimal> N_TBSW { get; set; }
        public Nullable<decimal> N_YXSC { get; set; }
        public Nullable<decimal> N_PSL { get; set; }
    }
}
