//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RTRPT_PUMP_HIS
    {
        public int N_ID { get; set; }
        public string S_DRAI_PUMP_ID { get; set; }
        public string S_SNAME { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_TYPE { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_TYPE_FEAT { get; set; }
        public Nullable<System.DateTime> T_STIME { get; set; }
        public Nullable<decimal> N_LIULIANG { get; set; }
        public Nullable<decimal> N_YULIANG { get; set; }
        public Nullable<decimal> N_SHUIWEI { get; set; }
        public Nullable<decimal> N_TAISHU { get; set; }
        public Nullable<decimal> N_KAIJITAISHU { get; set; }
        public Nullable<decimal> N_YEWEI { get; set; }
        public Nullable<decimal> N_WAIYEWEI { get; set; }
        public Nullable<short> N_RUNNING { get; set; }
    }
}
