//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RT_CONFIG
    {
        public decimal N_ID { get; set; }
        public string S_NO { get; set; }
        public string S_NAME { get; set; }
        public string S_DIC_VALUE { get; set; }
        public string S_DIC_UPNO { get; set; }
        public string S_KIND { get; set; }
        public Nullable<decimal> N_ORDERBY { get; set; }
        public Nullable<decimal> N_HASCHILD { get; set; }
        public string S_SYSNO { get; set; }
        public string S_ORGAN_NO { get; set; }
        public string S_ISUSE { get; set; }
        public string S_CREATEUSER { get; set; }
        public Nullable<System.DateTime> T_CREATEDATE { get; set; }
        public string S_UPDATEUSER { get; set; }
        public Nullable<System.DateTime> T_UPDATEDATE { get; set; }
        public string S_ISDEL { get; set; }
        public string S_MYTABLES { get; set; }
        public string S_MYCOLUMS { get; set; }
    }
}
