//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RVEVS_R
    {
        public string N_ID { get; set; }
        public string S_SCODE { get; set; }
        public string S_SNAME { get; set; }
        public string S_STTDRCD { get; set; }
        public Nullable<decimal> N_HTZ { get; set; }
        public Nullable<decimal> N_LTZ { get; set; }
        public Nullable<decimal> N_MXQ { get; set; }
        public Nullable<decimal> N_MNQ { get; set; }
        public Nullable<System.DateTime> T_MXQTM { get; set; }
        public Nullable<System.DateTime> T_MNQTM { get; set; }
        public Nullable<System.DateTime> T_IDTM { get; set; }
        public Nullable<System.DateTime> T_HTZTM { get; set; }
        public Nullable<System.DateTime> T_LTZTM { get; set; }
    }
}
