//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SCADA
    {
        public decimal OBJECTID_12 { get; set; }
        public Nullable<decimal> OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public string S_STATIONID { get; set; }
        public string S_SOURCEID { get; set; }
        public string S_STATIONNAME { get; set; }
        public string S_GRADE { get; set; }
        public string S_SOURCE { get; set; }
        public string S_TYPE { get; set; }
        public string S_SUBTYPE { get; set; }
        public string S_SQTYPE { get; set; }
        public string S_STATUS { get; set; }
        public Nullable<decimal> N_X { get; set; }
        public Nullable<decimal> N_Y { get; set; }
        public string S_DATASOURCE { get; set; }
        public string S_STATIONIDOLD { get; set; }
        public string S_OLDID { get; set; }
        public Nullable<decimal> N_CHECK_X { get; set; }
        public Nullable<decimal> N_CHECK_Y { get; set; }
        public Nullable<short> N_TOWNOWNED { get; set; }
    }
}
