//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SLFPDBP
    {
        public decimal OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public string S_EWCA_ID { get; set; }
        public string S_EWCA_NAME { get; set; }
        public Nullable<decimal> N_EWCA_AREA { get; set; }
        public string S_EWCA_RANGE { get; set; }
        public string S_DIST { get; set; }
        public string S_EWCA_REMARK { get; set; }
        public Nullable<short> N_ISUSE { get; set; }
    }
}
