//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TDRAISEWERAGESYSTEM
    {
        public decimal OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public string S_SYS_ID { get; set; }
        public string S_SYS_COM_ID { get; set; }
        public string S_LAYOUT_NUM { get; set; }
        public string S_SYS_NAME { get; set; }
        public Nullable<short> N_SYS_TYPE { get; set; }
        public Nullable<short> N_SYS_FLOW_KIND { get; set; }
        public string S_SYS_AREA_SERVICE { get; set; }
        public Nullable<decimal> N_SYS_AREA_FLOW { get; set; }
        public Nullable<decimal> N_SYS_STD_RAIN { get; set; }
        public Nullable<decimal> N_SYS_T_FACTOR { get; set; }
        public Nullable<decimal> N_SYS_FLOW_R_D { get; set; }
        public Nullable<decimal> N_SYS_FLOW_S_D { get; set; }
        public Nullable<decimal> N_SYS_FLOW_R_F { get; set; }
        public Nullable<decimal> N_SYS_FLOW_S_F { get; set; }
        public Nullable<decimal> N_SYS_DRAIN_PER { get; set; }
        public Nullable<decimal> N_SYS_DRAIN_L { get; set; }
        public Nullable<decimal> N_SYS_DRAIN_S { get; set; }
        public Nullable<decimal> N_SYS_DRAIN_INDU { get; set; }
        public Nullable<decimal> N_SYS_DENSITY_PER { get; set; }
        public string S_SYS_TO_RIV { get; set; }
        public string S_FACT_ID { get; set; }
        public Nullable<short> N_SYS_TYPE_BUILD { get; set; }
        public Nullable<short> N_SYS_LOCATION { get; set; }
        public string S_MANAGEUNIT { get; set; }
        public string S_DESIGNUNIT { get; set; }
        public string S_BUILDUNIT { get; set; }
        public string S_MAINTAINSUNIT { get; set; }
        public Nullable<System.DateTime> T_FINISHDATE { get; set; }
        public Nullable<System.DateTime> T_RUNDATE { get; set; }
        public Nullable<System.DateTime> T_REBUILDDATE { get; set; }
        public string S_MAPSHEETID { get; set; }
        public string S_IN_COM { get; set; }
        public Nullable<System.DateTime> T_IN_DATE { get; set; }
        public string S_IN_USE { get; set; }
        public Nullable<short> N_VERSIONID { get; set; }
        public string S_REMARK { get; set; }
        public string S_SID { get; set; }
        public Nullable<System.DateTime> T_BUILDDATE { get; set; }
        public Nullable<short> N_BUILDYEAR { get; set; }
        public Nullable<short> N_KEY_ID { get; set; }
        public string S_USERID { get; set; }
        public string S_SYS_DSN_ID { get; set; }
        public Nullable<decimal> N_SYS_DATE_RE { get; set; }
        public Nullable<decimal> N_SYS_N_FACTOR { get; set; }
        public string S_SYS_BORDLINE { get; set; }
        public Nullable<short> N_ISUSE { get; set; }
    }
}
