//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TXC
    {
        public decimal OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public string S_SHAPE { get; set; }
        public string S_RESERVOIR_ID { get; set; }
        public string S_RESERVOIR_NAME { get; set; }
        public string S_SYS_ID { get; set; }
        public string S_DRAI_PIPE_ID { get; set; }
        public string S_TDR_DRAI_PIPE_ID { get; set; }
        public string S_RESERVOIR_LOC { get; set; }
        public string S_PHONE { get; set; }
        public string S_POST_CODE { get; set; }
        public string S_RESERVOIR_TYPE { get; set; }
        public Nullable<decimal> N_RESERVOIR_DIAMETER { get; set; }
        public Nullable<decimal> N_RESERVOIR_WIDE { get; set; }
        public string S_RINSING_MODE { get; set; }
        public string S_EMPTY_MODE { get; set; }
        public Nullable<decimal> N_AMOUNT { get; set; }
        public Nullable<decimal> N_RESERVOIR_CUBAGE { get; set; }
        public Nullable<short> N_IN_TYPE { get; set; }
        public string S_OUT_TYPE { get; set; }
        public Nullable<decimal> N_LEVEL_MAX { get; set; }
        public Nullable<decimal> N_LEVEL_MIN { get; set; }
        public Nullable<decimal> N_FLOW_DSN { get; set; }
        public string S_DESC { get; set; }
        public Nullable<short> N_BUILDSTATE { get; set; }
        public Nullable<short> N_RINGROAD { get; set; }
        public string S_MANAGEUNIT { get; set; }
        public string S_DESIGNUNIT { get; set; }
        public string S_BUILDUNIT { get; set; }
        public string S_MAINTAINSUNIT { get; set; }
        public Nullable<System.DateTime> D_FINISHDATE { get; set; }
        public Nullable<System.DateTime> D_RUNDATE { get; set; }
        public Nullable<System.DateTime> D_REBUILDDATE { get; set; }
        public string S_MAPSHEETID { get; set; }
        public string S_IN_COM { get; set; }
        public Nullable<System.DateTime> D_IN_DATE { get; set; }
        public string S_IN_USE { get; set; }
        public Nullable<decimal> N_VERSIONID { get; set; }
        public string S_REMARK { get; set; }
        public Nullable<short> N_BUILDYEAR { get; set; }
        public Nullable<short> N_DISTRICT { get; set; }
        public Nullable<short> N_TOWNOWNED { get; set; }
        public Nullable<short> N_THEIRSYSTEM { get; set; }
        public string S_KZDJ { get; set; }
        public string S_X { get; set; }
        public string S_Y { get; set; }
        public Nullable<short> N_RESERVOIR_KIND { get; set; }
        public Nullable<short> N_ISUSE { get; set; }
    }
}
