//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WAS_R
    {
        public decimal N_ID { get; set; }
        public string S_SNAME { get; set; }
        public string S_SCODE { get; set; }
        public Nullable<System.DateTime> T_TM { get; set; }
        public Nullable<decimal> N_UPZ { get; set; }
        public Nullable<decimal> N_DWZ { get; set; }
        public Nullable<decimal> N_TGTQ { get; set; }
        public string S_MSQMT { get; set; }
        public string S_SUPWPTN { get; set; }
        public string S_SDWWPTN { get; set; }
        public string S_SWCHRCD { get; set; }
        public Nullable<decimal> N_DOOR1 { get; set; }
        public Nullable<decimal> N_DOOR2 { get; set; }
        public Nullable<decimal> N_DOOR3 { get; set; }
        public Nullable<decimal> N_DOOR4 { get; set; }
        public Nullable<decimal> N_DOOR5 { get; set; }
        public Nullable<decimal> N_DOOR6 { get; set; }
        public Nullable<decimal> N_DOOR7 { get; set; }
        public Nullable<decimal> N_DOOR8 { get; set; }
        public Nullable<decimal> N_DOOR9 { get; set; }
        public Nullable<decimal> N_DOOR10 { get; set; }
        public Nullable<decimal> N_DOOR11 { get; set; }
        public Nullable<decimal> N_DOOR12 { get; set; }
        public Nullable<decimal> N_DOOR13 { get; set; }
        public Nullable<decimal> N_DOOR14 { get; set; }
        public Nullable<decimal> N_DOOR15 { get; set; }
        public Nullable<short> N_DOORAMOUNT { get; set; }
        public Nullable<short> N_GTOPNUM { get; set; }
    }
}
