//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WASEVS_R3
    {
        public decimal N_ID { get; set; }
        public string S_SNAME { get; set; }
        public string S_SCODE { get; set; }
        public Nullable<System.DateTime> T_IDTM { get; set; }
        public string S_STTDRCD { get; set; }
        public Nullable<decimal> N_HTUPZ { get; set; }
        public Nullable<decimal> N_LTUPZ { get; set; }
        public Nullable<decimal> N_MXGTQ { get; set; }
        public Nullable<decimal> N_MNGTQ { get; set; }
        public Nullable<decimal> N_HTDWZ { get; set; }
        public Nullable<decimal> N_LTDWZ { get; set; }
        public Nullable<System.DateTime> T_HTUPZTM { get; set; }
        public Nullable<System.DateTime> T_LTUPZTM { get; set; }
        public Nullable<System.DateTime> T_MXGTQTM { get; set; }
        public Nullable<System.DateTime> T_MNGTQTM { get; set; }
        public Nullable<System.DateTime> T_HTDWZTM { get; set; }
        public Nullable<System.DateTime> T_LTDWZTM { get; set; }
    }
}
