//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WQ
    {
        public decimal OBJECTID { get; set; }
        public string S_XTBM { get; set; }
        public string S_POLDER_ID { get; set; }
        public string S_POLDER_NAME { get; set; }
        public string N_DIST_ID { get; set; }
        public string S_VILLAGE_ID { get; set; }
        public string S_EWCA_ID { get; set; }
        public Nullable<decimal> N_POLDER_DRATYPE { get; set; }
        public Nullable<System.DateTime> T_POLDER_TIME_BLD { get; set; }
        public Nullable<decimal> N_POLDER_AREA_SUM { get; set; }
        public Nullable<decimal> N_POLDER_AREA_3_5 { get; set; }
        public Nullable<decimal> N_POLDER_AREA_3_2 { get; set; }
        public Nullable<decimal> N_POLDER_AREA_3_23 { get; set; }
        public Nullable<decimal> N_POLDER_LENGTH_D { get; set; }
        public Nullable<decimal> N_POLDER_WIDTH_DP { get; set; }
        public Nullable<decimal> N_POLDER_HIGHT_DP { get; set; }
        public Nullable<decimal> N_POLDER_LENGTH_REV { get; set; }
        public Nullable<decimal> N_POLDER_TNUM_DE { get; set; }
        public Nullable<decimal> N_POLDER_FLOW_SUM { get; set; }
        public Nullable<decimal> N_POLDER_CAPA_SUM { get; set; }
        public Nullable<decimal> N_POLDER_DRAINCRITE { get; set; }
        public Nullable<decimal> N_POLDER_NUM_LOCK { get; set; }
        public Nullable<decimal> S_POLDER_TWIDTH_LOCK { get; set; }
        public Nullable<decimal> N_POLDER_NUM_GATE { get; set; }
        public Nullable<decimal> S_POLDER_TWIDTH_GATE { get; set; }
        public Nullable<decimal> N_POLDER_NUM_CUVT { get; set; }
        public string S_POLDER_REMARK { get; set; }
        public Nullable<short> N_TOWNOWNED { get; set; }
    }
}
