//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DATADIRECTORY
    {
        public decimal ID { get; set; }
        public string S_NO { get; set; }
        public string S_NAME { get; set; }
        public string S_PARENTNO { get; set; }
        public Nullable<decimal> S_ISUSE { get; set; }
        public Nullable<System.DateTime> S_CREATEDATE { get; set; }
        public string REMARK { get; set; }
        public string ICON { get; set; }
        public Nullable<decimal> SORT { get; set; }
        public string URL { get; set; }
    }
}
