//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DATASERVER
    {
        public string ID { get; set; }
        public string SERVERNAME { get; set; }
        public Nullable<decimal> DATATYPE { get; set; }
        public Nullable<decimal> RELEASETYPE { get; set; }
        public Nullable<decimal> ISSUED { get; set; }
        public string PUBLISHER { get; set; }
        public Nullable<System.DateTime> RELEASEDATE { get; set; }
        public string CONTACTNUMBER { get; set; }
        public Nullable<decimal> SERVICESSTATUS { get; set; }
        public string SERVICEADDRESS { get; set; }
        public string THUMBNAIL { get; set; }
        public string SERVICEDESCRIPTION { get; set; }
        public string SERVICEFORMAT { get; set; }
        public Nullable<decimal> SERVICETYPE { get; set; }
    }
}
