//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DATAINTEGRITY
    {
        public string ST_STATIONID { get; set; }
        public Nullable<System.DateTime> DT_TIME { get; set; }
        public Nullable<decimal> NM_RAINVALUE { get; set; }
        public string ST_STATIONNAME { get; set; }
        public string ST_ZDTYPE { get; set; }
        public string ST_TYPE { get; set; }
        public decimal SID { get; set; }
        public Nullable<System.DateTime> DT_NOWTIME { get; set; }
    }
}
