//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ITEM
    {
        public decimal N_ITEMID { get; set; }
        public string S_TYPE { get; set; }
        public string N_HOSTID { get; set; }
        public string S_NAME { get; set; }
        public string S_KEY { get; set; }
        public string S_DELAY { get; set; }
        public string S_UNIT { get; set; }
        public string S_DESCRIPTION { get; set; }
        public Nullable<decimal> S_FLAGS { get; set; }
        public string S_KIND { get; set; }
        public string S_SOURCE { get; set; }
        public string S_ALERT { get; set; }
        public Nullable<decimal> N_MAXVLAUE { get; set; }
        public Nullable<decimal> N_MINVLAUE { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE { get; set; }
    }
}
