//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_YULIANG_STATION
    {
        public string ST_STATIONID { get; set; }
        public string ST_STATIONNAME { get; set; }
        public string ST_OLDID { get; set; }
        public string ST_TYPENAME { get; set; }
        public string ST_SOURCE { get; set; }
        public Nullable<decimal> XX { get; set; }
        public Nullable<decimal> YY { get; set; }
        public string S_DIST { get; set; }
        public string OBJECTID { get; set; }
    }
}
