//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APP_DRAINPUMP
    {
        public decimal OBJECTID { get; set; }
        public string S_DRAI_PUMP_ID { get; set; }
        public string S_SYS_ID { get; set; }
        public string S_SYS_NAME { get; set; }
        public string S_DRAI_PUMP_NAME { get; set; }
        public Nullable<short> N_DRAI_PUMP_TYPE { get; set; }
        public Nullable<short> N_DRAI_PUMP_TYPE_FEAT { get; set; }
        public string S_DRAI_PUMP_ADD { get; set; }
        public string S_DRAI_PUMP_PHONE { get; set; }
        public string S_DRAI_PUMP_POST_CODE { get; set; }
        public Nullable<short> N_DRAI_PUMP_STATE { get; set; }
        public Nullable<short> N_RINGROAD { get; set; }
        public string S_DRAI_PUMP_COM_DSN { get; set; }
        public string S_DRAI_PUMP_COM_BUILD { get; set; }
        public string S_DRAI_PUMP_COM_MNG { get; set; }
        public string S_MAINTAINSUNIT { get; set; }
        public Nullable<System.DateTime> T_FINISHDATE { get; set; }
        public Nullable<System.DateTime> T_RUNDATE { get; set; }
        public Nullable<System.DateTime> T_REBUILDDATE { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_FLOW_DSN_Y { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_FLOW_DSN_W { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_FLOW_FACT_Y { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_FLOW_FACT_W { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_POW_DSN_Y { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_POW_DSN_W { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_POW_FACT_Y { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_POW_FACT_W { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_POW_SUM_Y { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_POW_SUM_W { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_LEVEL_DSN_Y { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_LEVEL_DSN_W { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_LEVEL_MAX_Y { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_LEVEL_MAX_W { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_LEVEL_MIN_Y { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_LEVEL_MIN_W { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_LEVEL_MAX_Y_DES { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_LEVEL_MAX_W_DES { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_LEVEL_MIN_Y_DES { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_LEVEL_MIN_W_DES { get; set; }
        public Nullable<decimal> N_DRAI_PUMP_AREA_USE { get; set; }
        public string S_DRAI_PUMP_PLAN { get; set; }
        public string S_DRAI_PUMP_PROFILE { get; set; }
        public Nullable<decimal> N_GRILLPLATX { get; set; }
        public Nullable<decimal> N_GRILLPLATY { get; set; }
        public Nullable<decimal> N_GRILLPLATELEV { get; set; }
        public Nullable<decimal> N_GROUNDELEV { get; set; }
        public Nullable<decimal> N_DESRAINSTORMREP { get; set; }
        public Nullable<decimal> N_DESCOEFFICIENT { get; set; }
        public Nullable<decimal> N_SERVICEAREA { get; set; }
        public string S_DRAI_PUMP_TO_RIV { get; set; }
        public string S_OUTLET_ID { get; set; }
        public string S_MAPSHEETID { get; set; }
        public Nullable<short> N_DISTRICT { get; set; }
        public Nullable<short> N_TOWNOWNED { get; set; }
        public string S_JIANSHEDANWEI { get; set; }
        public Nullable<System.DateTime> T_BUILDDATE { get; set; }
        public Nullable<short> N_BUILDYEAR { get; set; }
        public Nullable<decimal> S_JIANZHUMIANJI { get; set; }
        public string S_YIJISHUIDIAN { get; set; }
        public Nullable<decimal> N_YIJISHUIDIANBIAOGAO { get; set; }
        public Nullable<decimal> N_BENGZHANSHIWAIDIPINGBIAOGAO { get; set; }
        public string S_ZHUGUANDANWEI { get; set; }
        public string S_TUDIZHENGBIANHAO { get; set; }
        public string S_JUNGONGJUESUANJIA { get; set; }
        public string S_SERVICERANGE_E { get; set; }
        public string S_SERVICERANGE_W { get; set; }
        public string S_SERVICERANGE_S { get; set; }
        public string S_SERVICERANGE_N { get; set; }
        public Nullable<decimal> N_ZHANDIMIANJI { get; set; }
        public Nullable<decimal> N_JIANGYUKAICHESHUIWEI { get; set; }
        public Nullable<decimal> N_JIANGYUTINGCHESHUIWEI { get; set; }
        public Nullable<decimal> N_FANGXUNKAICHESHUIWEI { get; set; }
        public Nullable<decimal> N_FANGXUNTINGCHESHUIWEI { get; set; }
        public Nullable<decimal> N_JIELIUJIANGYUKAICHESHUIWEI { get; set; }
        public Nullable<decimal> N_JIELIUJIANGYUTINGCHESHUIWEI { get; set; }
        public Nullable<decimal> N_JIELIUHANLIUKAICHESHUIWEI { get; set; }
        public Nullable<decimal> N_JIELIUHANLIUTINGCHESHUIWEI { get; set; }
        public string S_KANGZHENDENGJI { get; set; }
        public string S_IN_COM { get; set; }
        public Nullable<System.DateTime> T_IN_DATE { get; set; }
        public string S_IN_USE { get; set; }
        public Nullable<decimal> N_VERSIONID { get; set; }
        public string S_REMARK { get; set; }
        public Nullable<short> N_KEY_ID { get; set; }
        public string S_USERID { get; set; }
        public string S_X { get; set; }
        public string S_Y { get; set; }
        public string S_PAIFANGKOUMC { get; set; }
        public string S_PAIFANGKOUXY { get; set; }
        public string S_SJGLDW { get; set; }
        public Nullable<short> N_GRADE { get; set; }
        public string S_SFJL { get; set; }
        public Nullable<decimal> N_JLLL { get; set; }
        public Nullable<decimal> N_JLGL { get; set; }
        public Nullable<decimal> N_FLOW2016 { get; set; }
        public Nullable<decimal> N_POWER2016 { get; set; }
        public Nullable<short> N_CODE { get; set; }
        public Nullable<short> N_ISUSE { get; set; }
        public string S_XTBM { get; set; }
        public Nullable<decimal> N_THEIRSYSTEM { get; set; }
        public string WBID { get; set; }
        public string FULLPATH { get; set; }
        public Nullable<decimal> N_SHUIWEI { get; set; }
        public Nullable<decimal> N_TAISHU { get; set; }
        public Nullable<decimal> N_KAIJITAISHU { get; set; }
        public string S_EXTNO { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> S_NHZG { get; set; }
        public Nullable<decimal> S_WHZG { get; set; }
    }
}
