//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APP_WQAMD
    {
        public decimal N_ID { get; set; }
        public string S_SCODE { get; set; }
        public string S_SNAME { get; set; }
        public string S_PRPNM { get; set; }
        public string S_LYNM { get; set; }
        public string S_WBTP { get; set; }
        public Nullable<System.DateTime> T_SPT { get; set; }
        public Nullable<decimal> N_WTMP { get; set; }
        public Nullable<decimal> N_PH { get; set; }
        public Nullable<int> N_COND { get; set; }
        public Nullable<decimal> N_TURB { get; set; }
        public Nullable<decimal> N_DOX { get; set; }
        public Nullable<decimal> N_CODMN { get; set; }
        public Nullable<decimal> N_CODCR { get; set; }
        public Nullable<decimal> N_BOD5 { get; set; }
        public Nullable<decimal> N_SO4 { get; set; }
        public Nullable<decimal> N_TIC { get; set; }
        public Nullable<decimal> N_TN { get; set; }
        public Nullable<decimal> N_NH3N { get; set; }
        public Nullable<decimal> N_NH3 { get; set; }
        public Nullable<decimal> N_NO2 { get; set; }
        public Nullable<decimal> N_NO3 { get; set; }
        public Nullable<decimal> N_KN { get; set; }
        public Nullable<decimal> N_S2 { get; set; }
        public Nullable<decimal> N_CN { get; set; }
        public Nullable<decimal> N_TCN { get; set; }
        public Nullable<decimal> N_EP { get; set; }
        public Nullable<decimal> N_TP { get; set; }
        public Nullable<decimal> N_YP { get; set; }
        public Nullable<decimal> N_PO4 { get; set; }
        public Nullable<decimal> N_DTP { get; set; }
        public Nullable<decimal> N_F { get; set; }
        public Nullable<decimal> N_CL { get; set; }
        public Nullable<decimal> N_FCHL { get; set; }
        public Nullable<decimal> N_ACHL { get; set; }
        public Nullable<decimal> N_TCHL { get; set; }
        public Nullable<decimal> N_I { get; set; }
        public Nullable<decimal> N_SI { get; set; }
        public Nullable<decimal> N_B { get; set; }
        public Nullable<decimal> N_DZHWY { get; set; }
        public string S_NT { get; set; }
    }
}
