//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PM_PROJECT
    {
        public decimal PROJECT_ID { get; set; }
        public Nullable<decimal> BUDGET_ID { get; set; }
        public string BUDGET_NAME { get; set; }
        public string PROJECT_NO { get; set; }
        public string PROJECT_NAME { get; set; }
        public Nullable<short> START_YEAR { get; set; }
        public string GIS_POSITION { get; set; }
        public string PROJECT_LOCATION { get; set; }
        public string PROJECT_STAGE_NAME { get; set; }
        public string HANDLE_USER_ID { get; set; }
        public string HANDLE_USER_NAME { get; set; }
        public string CHARGE_LEAD_ID { get; set; }
        public string CHARGE_LEAD_NAME { get; set; }
        public string REMARK { get; set; }
        public string CREATED_BY_USER_ID { get; set; }
        public string CREATED_BY_USER_NAME { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY_USER_ID { get; set; }
        public string LAST_UPDATED_BY_USER_NAME { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> PROCESS_PERCENT { get; set; }
        public string HANDLE_DEPT_ID { get; set; }
        public string HANDLE_DEPT_NAME { get; set; }
        public string PROJECT_MAIN_NAME { get; set; }
        public string PRE_USER_ID { get; set; }
        public string PRE_USER_NAME { get; set; }
    }
}
