//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExampleForOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 水闸
    {
        public string S_SLUICE_ID { get; set; }
        public string S_SLUICE_NAME { get; set; }
        public Nullable<decimal> N_SLUICE_TYPE { get; set; }
        public Nullable<decimal> N_DIST_ID { get; set; }
        public Nullable<decimal> N_TOWN_ID { get; set; }
        public string S_SLUICE_LOCATION { get; set; }
        public string S_RIV_ID { get; set; }
        public string S_EWCA_ID { get; set; }
        public string S_POLDER_ID { get; set; }
        public Nullable<decimal> N_SLUICE_LEVEL_UMAX { get; set; }
        public Nullable<decimal> N_SLUICE_LEVEL_UMIN { get; set; }
        public Nullable<decimal> N_SLUICE_LEVEL_DMAX { get; set; }
        public Nullable<decimal> N_SLUICE_LEVEL_DMIN { get; set; }
        public Nullable<decimal> N_SLUICE_FLOW_DMAX { get; set; }
        public Nullable<decimal> N_SLUICE_FLOW_IMAX { get; set; }
        public Nullable<decimal> N_SLUICE_ALT_GB { get; set; }
        public Nullable<decimal> N_SLUICE_ALT_GT { get; set; }
        public Nullable<decimal> N_SLUICE_WIDTH_LG { get; set; }
        public Nullable<decimal> N_SLUICE_NUM_SG { get; set; }
        public string S_SLUICE_WIDTH_SG { get; set; }
        public Nullable<decimal> N_SLUICE_WIDTH_SUM { get; set; }
        public Nullable<System.DateTime> T_SLUICE_TIME_BLD { get; set; }
        public string S_SLUICE_COM_DSN { get; set; }
        public string S_SLUICE_COM_BLD { get; set; }
        public string S_SLUICE_COM_SUP { get; set; }
        public string S_SLUICE_COM_MNG { get; set; }
        public Nullable<System.DateTime> T_SLUICE_TIME_RBD { get; set; }
        public string S_SLUICE_PICTURE { get; set; }
        public string S_SLUICE_TYPE_HST { get; set; }
        public string S_SLUICE_TYPE_GTE { get; set; }
        public Nullable<decimal> N_SLUICE_GRADE_NAV { get; set; }
        public Nullable<decimal> N_SLUICE_LENGTH_CHA { get; set; }
        public Nullable<decimal> N_SLUICE_WIDTH_CHA { get; set; }
        public string S_SLUICE_REMARK { get; set; }
        public string S_SLUICE_TYPE_HST_DL { get; set; }
        public Nullable<decimal> N_COORD_X { get; set; }
        public Nullable<decimal> N_COORD_Y { get; set; }
        public string S_MILES_RIV_CODE { get; set; }
        public Nullable<decimal> N_ID { get; set; }
        public Nullable<decimal> N_FENXIAN { get; set; }
        public Nullable<decimal> N_GRADE { get; set; }
        public string S_WAIHE { get; set; }
        public Nullable<decimal> N_ZILIAO { get; set; }
        public Nullable<System.DateTime> T_COMPLETIONDATE { get; set; }
        public string S_BRIDGE_BZ { get; set; }
        public Nullable<decimal> N_BRIDGEBOTTOM_HIGH { get; set; }
        public Nullable<decimal> N_BRIDGE_WIDTH { get; set; }
        public Nullable<decimal> N_BRIDGE_LONG { get; set; }
        public Nullable<decimal> N_BENEFIT_GG { get; set; }
        public Nullable<decimal> N_BENEFIT_PAI { get; set; }
        public string S_USE { get; set; }
        public string S_RIV_NAME { get; set; }
        public Nullable<decimal> N_HEADBAY { get; set; }
        public Nullable<decimal> N_TAILBAY { get; set; }
        public Nullable<decimal> N_JACKUP { get; set; }
        public string S_GATESTRUCTURE { get; set; }
        public Nullable<decimal> N_TRANSCAPACITY { get; set; }
        public string S_ACCOUNTNUMBER { get; set; }
        public string S_SLUICE_MODEL { get; set; }
        public Nullable<decimal> S_SLUICE_NUMBER { get; set; }
        public Nullable<decimal> N_PUMP_MOTORPOWER { get; set; }
        public Nullable<decimal> N_PUMP_MOTORNUMBER { get; set; }
        public Nullable<decimal> N_WATERPUMPFLOW { get; set; }
        public string S_FCZNUMBER { get; set; }
        public Nullable<decimal> N_CZAREA { get; set; }
        public string S_TDZNUMBER { get; set; }
        public Nullable<decimal> N_TDAREA { get; set; }
    }
}
