//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExample.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExample.Models;
    public partial class AttributesController:ODataController
    {
            private odataEntities db = new odataEntities();
    
            // GET: odata/Attributes
            [EnableQuery]
            public IQueryable<Attributes> GetAttributes()
            {
                return db.Attributes;
            }
    
            // GET: odata/Attributes(5)
            [EnableQuery]
            public SingleResult<Attributes> GetAttributes([FromODataUri] int key)
            {
                return SingleResult.Create(db.Attributes.Where(w => w.Id == key));
            }
    
            // PUT: odata/Attributes(5)
            public IHttpActionResult Put([FromODataUri] int key, Delta<Attributes> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                Attributes Attributes = db.Attributes.Find(key);
                if (Attributes == null)
                {
                    return NotFound();
                }
    
                patch.Put(Attributes);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AttributesExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(Attributes);
            }
    
            // POST: odata/Attributes
            public IHttpActionResult Post(Attributes Attributes)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.Attributes.Add(Attributes);
                db.SaveChanges();
    
                return Created(Attributes);
            }
    
            // PATCH: odata/Attributes(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] int key, Delta<Attributes> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                Attributes Attributes = db.Attributes.Find(key);
                if (Attributes == null)
                {
                    return NotFound();
                }
    
                patch.Patch(Attributes);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AttributesExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(Attributes);
            }
    
            // DELETE: odata/Attributes(5)
            public IHttpActionResult Delete([FromODataUri] int key)
            {
                Attributes Attributes = db.Attributes.Find(key);
                if (Attributes == null)
                {
                    return NotFound();
                }
    
                db.Attributes.Remove(Attributes);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool AttributesExists(int key)
            {
                return db.Attributes.Count(e => e.Id == key) > 0;
            }
      
    }
}
