//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExample.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExample.Models;
    public partial class ClassTabController:ODataController
    {
            private odataEntities db = new odataEntities();
    
            // GET: odata/ClassTab
            [EnableQuery]
            public IQueryable<ClassTab> GetClassTab()
            {
                return db.ClassTab;
            }
    
            // GET: odata/ClassTab(5)
            [EnableQuery]
            public SingleResult<ClassTab> GetClassTab([FromODataUri] int key)
            {
                return SingleResult.Create(db.ClassTab.Where(w => w.id == key));
            }
    
            // PUT: odata/ClassTab(5)
            public IHttpActionResult Put([FromODataUri] int key, Delta<ClassTab> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                ClassTab ClassTab = db.ClassTab.Find(key);
                if (ClassTab == null)
                {
                    return NotFound();
                }
    
                patch.Put(ClassTab);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassTabExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(ClassTab);
            }
    
            // POST: odata/ClassTab
            public IHttpActionResult Post(ClassTab ClassTab)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.ClassTab.Add(ClassTab);
                db.SaveChanges();
    
                return Created(ClassTab);
            }
    
            // PATCH: odata/ClassTab(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] int key, Delta<ClassTab> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                ClassTab ClassTab = db.ClassTab.Find(key);
                if (ClassTab == null)
                {
                    return NotFound();
                }
    
                patch.Patch(ClassTab);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassTabExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(ClassTab);
            }
    
            // DELETE: odata/ClassTab(5)
            public IHttpActionResult Delete([FromODataUri] int key)
            {
                ClassTab ClassTab = db.ClassTab.Find(key);
                if (ClassTab == null)
                {
                    return NotFound();
                }
    
                db.ClassTab.Remove(ClassTab);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool ClassTabExists(int key)
            {
                return db.ClassTab.Count(e => e.id == key) > 0;
            }
      
    }
}
