//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExample.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExample.Models;
    public partial class EMPController:ODataController
    {
            private odataEntities db = new odataEntities();
    
            // GET: odata/EMP
            [EnableQuery]
            public IQueryable<EMP> GetEMP()
            {
                return db.EMP;
            }
    
            // GET: odata/EMP(5)
            [EnableQuery]
            public SingleResult<EMP> GetEMP([FromODataUri] string key)
            {
                return SingleResult.Create(db.EMP.Where(w => w.EID == key));
            }
    
            // PUT: odata/EMP(5)
            public IHttpActionResult Put([FromODataUri] string key, Delta<EMP> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                EMP EMP = db.EMP.Find(key);
                if (EMP == null)
                {
                    return NotFound();
                }
    
                patch.Put(EMP);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EMPExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(EMP);
            }
    
            // POST: odata/EMP
            public IHttpActionResult Post(EMP EMP)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.EMP.Add(EMP);
                db.SaveChanges();
    
                return Created(EMP);
            }
    
            // PATCH: odata/EMP(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] string key, Delta<EMP> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                EMP EMP = db.EMP.Find(key);
                if (EMP == null)
                {
                    return NotFound();
                }
    
                patch.Patch(EMP);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EMPExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(EMP);
            }
    
            // DELETE: odata/EMP(5)
            public IHttpActionResult Delete([FromODataUri] string key)
            {
                EMP EMP = db.EMP.Find(key);
                if (EMP == null)
                {
                    return NotFound();
                }
    
                db.EMP.Remove(EMP);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool EMPExists(string key)
            {
                return db.EMP.Count(e => e.EID == key) > 0;
            }
      
    }
}
