//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExample.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExample.Models;
    public partial class StudentController:ODataController
    {
            private odataEntities db = new odataEntities();
    
            // GET: odata/Student
            [EnableQuery]
            public IQueryable<Student> GetStudent()
            {
                return db.Student;
            }
    
            // GET: odata/Student(5)
            [EnableQuery]
            public SingleResult<Student> GetStudent([FromODataUri] int key)
            {
                return SingleResult.Create(db.Student.Where(w => w.Id == key));
            }
    
            // PUT: odata/Student(5)
            public IHttpActionResult Put([FromODataUri] int key, Delta<Student> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                Student Student = db.Student.Find(key);
                if (Student == null)
                {
                    return NotFound();
                }
    
                patch.Put(Student);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(Student);
            }
    
            // POST: odata/Student
            public IHttpActionResult Post(Student Student)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.Student.Add(Student);
                db.SaveChanges();
    
                return Created(Student);
            }
    
            // PATCH: odata/Student(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] int key, Delta<Student> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                Student Student = db.Student.Find(key);
                if (Student == null)
                {
                    return NotFound();
                }
    
                patch.Patch(Student);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(Student);
            }
    
            // DELETE: odata/Student(5)
            public IHttpActionResult Delete([FromODataUri] int key)
            {
                Student Student = db.Student.Find(key);
                if (Student == null)
                {
                    return NotFound();
                }
    
                db.Student.Remove(Student);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool StudentExists(int key)
            {
                return db.Student.Count(e => e.Id == key) > 0;
            }
      
    }
}
