//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExample.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExample.Models;
    public partial class testController:ODataController
    {
            private odataEntities db = new odataEntities();
    
            // GET: odata/test
            [EnableQuery]
            public IQueryable<test> Gettest()
            {
                return db.test;
            }
    
            // GET: odata/test(5)
            [EnableQuery]
            public SingleResult<test> Gettest([FromODataUri] int key)
            {
                return SingleResult.Create(db.test.Where(w => w.id == key));
            }
    
            // PUT: odata/test(5)
            public IHttpActionResult Put([FromODataUri] int key, Delta<test> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                test test = db.test.Find(key);
                if (test == null)
                {
                    return NotFound();
                }
    
                patch.Put(test);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!testExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(test);
            }
    
            // POST: odata/test
            public IHttpActionResult Post(test test)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.test.Add(test);
                db.SaveChanges();
    
                return Created(test);
            }
    
            // PATCH: odata/test(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] int key, Delta<test> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                test test = db.test.Find(key);
                if (test == null)
                {
                    return NotFound();
                }
    
                patch.Patch(test);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!testExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(test);
            }
    
            // DELETE: odata/test(5)
            public IHttpActionResult Delete([FromODataUri] int key)
            {
                test test = db.test.Find(key);
                if (test == null)
                {
                    return NotFound();
                }
    
                db.test.Remove(test);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool testExists(int key)
            {
                return db.test.Count(e => e.id == key) > 0;
            }
      
    }
}
