//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExample.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExample.Models;
    public partial class WORKController:ODataController
    {
            private odataEntities db = new odataEntities();
    
            // GET: odata/WORK
            [EnableQuery]
            public IQueryable<WORK> GetWORK()
            {
                return db.WORK;
            }
    
            // GET: odata/WORK(5)
            [EnableQuery]
            public SingleResult<WORK> GetWORK([FromODataUri] string key)
            {
                return SingleResult.Create(db.WORK.Where(w => w.DID == key));
            }
    
            // PUT: odata/WORK(5)
            public IHttpActionResult Put([FromODataUri] string key, Delta<WORK> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                WORK WORK = db.WORK.Find(key);
                if (WORK == null)
                {
                    return NotFound();
                }
    
                patch.Put(WORK);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WORKExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(WORK);
            }
    
            // POST: odata/WORK
            public IHttpActionResult Post(WORK WORK)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.WORK.Add(WORK);
                db.SaveChanges();
    
                return Created(WORK);
            }
    
            // PATCH: odata/WORK(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] string key, Delta<WORK> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                WORK WORK = db.WORK.Find(key);
                if (WORK == null)
                {
                    return NotFound();
                }
    
                patch.Patch(WORK);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WORKExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(WORK);
            }
    
            // DELETE: odata/WORK(5)
            public IHttpActionResult Delete([FromODataUri] string key)
            {
                WORK WORK = db.WORK.Find(key);
                if (WORK == null)
                {
                    return NotFound();
                }
    
                db.WORK.Remove(WORK);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool WORKExists(string key)
            {
                return db.WORK.Count(e => e.DID == key) > 0;
            }
      
    }
}
