//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataExample.Controllers
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.OData;
    using System.Web.Http.OData.Routing;
    using OdataExample.Models;
    public partial class YHTABController:ODataController
    {
            private odataEntities db = new odataEntities();
    
            // GET: odata/YHTAB
            [EnableQuery]
            public IQueryable<YHTAB> GetYHTAB()
            {
                return db.YHTAB;
            }
    
            // GET: odata/YHTAB(5)
            [EnableQuery]
            public SingleResult<YHTAB> GetYHTAB([FromODataUri] int key)
            {
                return SingleResult.Create(db.YHTAB.Where(w => w.num == key));
            }
    
            // PUT: odata/YHTAB(5)
            public IHttpActionResult Put([FromODataUri] int key, Delta<YHTAB> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                YHTAB YHTAB = db.YHTAB.Find(key);
                if (YHTAB == null)
                {
                    return NotFound();
                }
    
                patch.Put(YHTAB);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!YHTABExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(YHTAB);
            }
    
            // POST: odata/YHTAB
            public IHttpActionResult Post(YHTAB YHTAB)
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                db.YHTAB.Add(YHTAB);
                db.SaveChanges();
    
                return Created(YHTAB);
            }
    
            // PATCH: odata/YHTAB(5)
            [AcceptVerbs("PATCH", "MERGE")]
            public IHttpActionResult Patch([FromODataUri] int key, Delta<YHTAB> patch)
            {
                Validate(patch.GetEntity());
    
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
    
                YHTAB YHTAB = db.YHTAB.Find(key);
                if (YHTAB == null)
                {
                    return NotFound();
                }
    
                patch.Patch(YHTAB);
    
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!YHTABExists(key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
    
                return Updated(YHTAB);
            }
    
            // DELETE: odata/YHTAB(5)
            public IHttpActionResult Delete([FromODataUri] int key)
            {
                YHTAB YHTAB = db.YHTAB.Find(key);
                if (YHTAB == null)
                {
                    return NotFound();
                }
    
                db.YHTAB.Remove(YHTAB);
                db.SaveChanges();
    
                return StatusCode(HttpStatusCode.NoContent);
            }
    
            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    
            private bool YHTABExists(int key)
            {
                return db.YHTAB.Count(e => e.num == key) > 0;
            }
      
    }
}
